root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  pre_cmd = ["cd web && pnpm build"]
  cmd = "CGO_ENABLED=1 go build -o ./tmp/main ./cmd/main.go"
  delay = 1500
  exclude_dir = ["assets", "tmp", "vendor", "web/dist", "web/node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "vue", "tsx", "ts", "css", "js", "json"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false