// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"time"
)



// APIKeyHandlerRouter defines the required methods for binding the api requests to a responses for the APIKeyHandler
// The APIKeyHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a APIKeyHandlerServicer to perform the required actions, then write the service results to the http response.
type APIKeyHandlerRouter interface { 
	GetAPIKeys(http.ResponseWriter, *http.Request)
	CreateAPIKey(http.ResponseWriter, *http.Request)
	DeleteAPIKey(http.ResponseWriter, *http.Request)
	UpdateAPIKey(http.ResponseWriter, *http.Request)
}
// AuditHandlerRouter defines the required methods for binding the api requests to a responses for the AuditHandler
// The AuditHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a AuditHandlerServicer to perform the required actions, then write the service results to the http response.
type AuditHandlerRouter interface { 
	GetAuditLogs(http.ResponseWriter, *http.Request)
	GetAuditMetrics(http.ResponseWriter, *http.Request)
}
// AuthHandlerRouter defines the required methods for binding the api requests to a responses for the AuthHandler
// The AuthHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a AuthHandlerServicer to perform the required actions, then write the service results to the http response.
type AuthHandlerRouter interface { 
	Login(http.ResponseWriter, *http.Request)
	Signup(http.ResponseWriter, *http.Request)
	Logout(http.ResponseWriter, *http.Request)
	RequestPasswordReset(http.ResponseWriter, *http.Request)
	ConfirmPasswordReset(http.ResponseWriter, *http.Request)
	RequestMagicLink(http.ResponseWriter, *http.Request)
	ConsumeMagicLink(http.ResponseWriter, *http.Request)
}
// CliHandlerRouter defines the required methods for binding the api requests to a responses for the CliHandler
// The CliHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a CliHandlerServicer to perform the required actions, then write the service results to the http response.
type CliHandlerRouter interface { 
	GetVaultsByAPIKey(http.ResponseWriter, *http.Request)
	GetVaultByAPIKey(http.ResponseWriter, *http.Request)
	GetVaultByNameAPIKey(http.ResponseWriter, *http.Request)
}
// ConfigHandlerRouter defines the required methods for binding the api requests to a responses for the ConfigHandler
// The ConfigHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a ConfigHandlerServicer to perform the required actions, then write the service results to the http response.
type ConfigHandlerRouter interface { 
	GetConfig(http.ResponseWriter, *http.Request)
}
// DefaultHandlerRouter defines the required methods for binding the api requests to a responses for the DefaultHandler
// The DefaultHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultHandlerServicer to perform the required actions, then write the service results to the http response.
type DefaultHandlerRouter interface { 
	Health(http.ResponseWriter, *http.Request)
}
// StatusHandlerRouter defines the required methods for binding the api requests to a responses for the StatusHandler
// The StatusHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a StatusHandlerServicer to perform the required actions, then write the service results to the http response.
type StatusHandlerRouter interface { 
	GetStatus(http.ResponseWriter, *http.Request)
}
// UserHandlerRouter defines the required methods for binding the api requests to a responses for the UserHandler
// The UserHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a UserHandlerServicer to perform the required actions, then write the service results to the http response.
type UserHandlerRouter interface { 
	GetCurrentUser(http.ResponseWriter, *http.Request)
}
// VaultHandlerRouter defines the required methods for binding the api requests to a responses for the VaultHandler
// The VaultHandlerRouter implementation should parse necessary information from the http request,
// pass the data to a VaultHandlerServicer to perform the required actions, then write the service results to the http response.
type VaultHandlerRouter interface { 
	GetVaults(http.ResponseWriter, *http.Request)
	CreateVault(http.ResponseWriter, *http.Request)
	GetVault(http.ResponseWriter, *http.Request)
	UpdateVault(http.ResponseWriter, *http.Request)
	DeleteVault(http.ResponseWriter, *http.Request)
}


// APIKeyHandlerServicer defines the api actions for the APIKeyHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type APIKeyHandlerServicer interface { 
	GetAPIKeys(context.Context, int32, int32) (ImplResponse, error)
	CreateAPIKey(context.Context, CreateApiKeyRequest) (ImplResponse, error)
	DeleteAPIKey(context.Context, int64) (ImplResponse, error)
	UpdateAPIKey(context.Context, int64, UpdateApiKeyRequest) (ImplResponse, error)
}


// AuditHandlerServicer defines the api actions for the AuditHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuditHandlerServicer interface { 
	GetAuditLogs(context.Context, int32, int32, time.Time, time.Time, string) (ImplResponse, error)
	GetAuditMetrics(context.Context) (ImplResponse, error)
}


// AuthHandlerServicer defines the api actions for the AuthHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuthHandlerServicer interface { 
	Login(context.Context, LoginRequest) (ImplResponse, error)
	Signup(context.Context, SignupRequest) (ImplResponse, error)
	Logout(context.Context) (ImplResponse, error)
	RequestPasswordReset(context.Context, PasswordResetRequest) (ImplResponse, error)
	ConfirmPasswordReset(context.Context, PasswordResetConfirmRequest) (ImplResponse, error)
	RequestMagicLink(context.Context, MagicLinkRequest) (ImplResponse, error)
	ConsumeMagicLink(context.Context, string) (ImplResponse, error)
}


// CliHandlerServicer defines the api actions for the CliHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CliHandlerServicer interface { 
	GetVaultsByAPIKey(context.Context) (ImplResponse, error)
	GetVaultByAPIKey(context.Context, string, string) (ImplResponse, error)
	GetVaultByNameAPIKey(context.Context, string, string) (ImplResponse, error)
}


// ConfigHandlerServicer defines the api actions for the ConfigHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ConfigHandlerServicer interface { 
	GetConfig(context.Context) (ImplResponse, error)
}


// DefaultHandlerServicer defines the api actions for the DefaultHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultHandlerServicer interface { 
	Health(context.Context) (ImplResponse, error)
}


// StatusHandlerServicer defines the api actions for the StatusHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type StatusHandlerServicer interface { 
	GetStatus(context.Context) (ImplResponse, error)
}


// UserHandlerServicer defines the api actions for the UserHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UserHandlerServicer interface { 
	GetCurrentUser(context.Context) (ImplResponse, error)
}


// VaultHandlerServicer defines the api actions for the VaultHandler service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type VaultHandlerServicer interface { 
	GetVaults(context.Context, int32, int32) (ImplResponse, error)
	CreateVault(context.Context, CreateVaultRequest) (ImplResponse, error)
	GetVault(context.Context, string) (ImplResponse, error)
	UpdateVault(context.Context, string, UpdateVaultRequest) (ImplResponse, error)
	DeleteVault(context.Context, string) (ImplResponse, error)
}
