// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// CliHandlerService is a service that implements the logic for the CliHandlerServicer
// This service should implement the business logic for every endpoint for the CliHandler API.
// Include any external packages or services that will be required by this service.
type CliHandlerService struct {
}

// NewCliHandlerService creates a default api service
func NewCliHandlerService() *CliHandlerService {
	return &CliHandlerService{}
}

// GetVaultsByAPIKey - 
func (s *CliHandlerService) GetVaultsByAPIKey(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetVaultsByAPIKey with the required logic for this service method.
	// Add api_cli_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []VaultLite{}) or use other options such as http.Ok ...
	// return Response(200, []VaultLite{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetVaultsByAPIKey method not implemented")
}

// GetVaultByAPIKey - 
func (s *CliHandlerService) GetVaultByAPIKey(ctx context.Context, uniqueId string, xEnableClientEncryption string) (ImplResponse, error) {
	// TODO - update GetVaultByAPIKey with the required logic for this service method.
	// Add api_cli_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Vault{}) or use other options such as http.Ok ...
	// return Response(200, Vault{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetVaultByAPIKey method not implemented")
}

// GetVaultByNameAPIKey - 
func (s *CliHandlerService) GetVaultByNameAPIKey(ctx context.Context, name string, xEnableClientEncryption string) (ImplResponse, error) {
	// TODO - update GetVaultByNameAPIKey with the required logic for this service method.
	// Add api_cli_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Vault{}) or use other options such as http.Ok ...
	// return Response(200, Vault{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetVaultByNameAPIKey method not implemented")
}
