// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"net/http"
	"strings"
)

// StatusHandlerController binds http requests to an api service and writes the service results to the http response
type StatusHandlerController struct {
	service StatusHandlerServicer
	errorHandler ErrorHandler
}

// StatusHandlerOption for how the controller is set up.
type StatusHandlerOption func(*StatusHandlerController)

// WithStatusHandlerErrorHandler inject ErrorHandler into controller
func WithStatusHandlerErrorHandler(h ErrorHandler) StatusHandlerOption {
	return func(c *StatusHandlerController) {
		c.errorHandler = h
	}
}

// NewStatusHandlerController creates a default api controller
func NewStatusHandlerController(s StatusHandlerServicer, opts ...StatusHandlerOption) *StatusHandlerController {
	controller := &StatusHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the StatusHandlerController
func (c *StatusHandlerController) Routes() Routes {
	return Routes{
		"GetStatus": Route{
			"GetStatus",
			strings.ToUpper("Get"),
			"/api/status",
			c.GetStatus,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the StatusHandlerController
func (c *StatusHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetStatus",
			strings.ToUpper("Get"),
			"/api/status",
			c.GetStatus,
		},
	}
}



// GetStatus - Get system status
func (c *StatusHandlerController) GetStatus(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetStatus(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
