// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"net/http"
	"strings"
)

// ConfigHandlerController binds http requests to an api service and writes the service results to the http response
type ConfigHandlerController struct {
	service ConfigHandlerServicer
	errorHandler ErrorHandler
}

// ConfigHandlerOption for how the controller is set up.
type ConfigHandlerOption func(*ConfigHandlerController)

// WithConfigHandlerErrorHandler inject ErrorHandler into controller
func WithConfigHandlerErrorHandler(h ErrorHandler) ConfigHandlerOption {
	return func(c *ConfigHandlerController) {
		c.errorHandler = h
	}
}

// NewConfigHandlerController creates a default api controller
func NewConfigHandlerController(s ConfigHandlerServicer, opts ...ConfigHandlerOption) *ConfigHandlerController {
	controller := &ConfigHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ConfigHandlerController
func (c *ConfigHandlerController) Routes() Routes {
	return Routes{
		"GetConfig": Route{
			"GetConfig",
			strings.ToUpper("Get"),
			"/api/config",
			c.GetConfig,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the ConfigHandlerController
func (c *ConfigHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetConfig",
			strings.ToUpper("Get"),
			"/api/config",
			c.GetConfig,
		},
	}
}



// GetConfig - Get public configuration
func (c *ConfigHandlerController) GetConfig(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetConfig(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
