// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// AuthHandlerService is a service that implements the logic for the AuthHandlerServicer
// This service should implement the business logic for every endpoint for the AuthHandler API.
// Include any external packages or services that will be required by this service.
type AuthHandlerService struct {
}

// NewAuthHandlerService creates a default api service
func NewAuthHandlerService() *AuthHandlerService {
	return &AuthHandlerService{}
}

// Login - 
func (s *AuthHandlerService) Login(ctx context.Context, loginRequest LoginRequest) (ImplResponse, error) {
	// TODO - update Login with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LoginResponse{}) or use other options such as http.Ok ...
	// return Response(200, LoginResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Login method not implemented")
}

// Signup - 
func (s *AuthHandlerService) Signup(ctx context.Context, signupRequest SignupRequest) (ImplResponse, error) {
	// TODO - update Signup with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SignupResponse{}) or use other options such as http.Ok ...
	// return Response(200, SignupResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Signup method not implemented")
}

// Logout - 
func (s *AuthHandlerService) Logout(ctx context.Context) (ImplResponse, error) {
	// TODO - update Logout with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Logout method not implemented")
}

// RequestPasswordReset - 
func (s *AuthHandlerService) RequestPasswordReset(ctx context.Context, passwordResetRequest PasswordResetRequest) (ImplResponse, error) {
	// TODO - update RequestPasswordReset with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EmailTokenResponse{}) or use other options such as http.Ok ...
	// return Response(200, EmailTokenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, EmailTokenResponse{}) or use other options such as http.Ok ...
	// return Response(429, EmailTokenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, EmailTokenResponse{}) or use other options such as http.Ok ...
	// return Response(500, EmailTokenResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequestPasswordReset method not implemented")
}

// ConfirmPasswordReset - 
func (s *AuthHandlerService) ConfirmPasswordReset(ctx context.Context, passwordResetConfirmRequest PasswordResetConfirmRequest) (ImplResponse, error) {
	// TODO - update ConfirmPasswordReset with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConfirmPasswordReset method not implemented")
}

// RequestMagicLink - 
func (s *AuthHandlerService) RequestMagicLink(ctx context.Context, magicLinkRequest MagicLinkRequest) (ImplResponse, error) {
	// TODO - update RequestMagicLink with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EmailTokenResponse{}) or use other options such as http.Ok ...
	// return Response(200, EmailTokenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, EmailTokenResponse{}) or use other options such as http.Ok ...
	// return Response(429, EmailTokenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, EmailTokenResponse{}) or use other options such as http.Ok ...
	// return Response(500, EmailTokenResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequestMagicLink method not implemented")
}

// ConsumeMagicLink - 
func (s *AuthHandlerService) ConsumeMagicLink(ctx context.Context, token string) (ImplResponse, error) {
	// TODO - update ConsumeMagicLink with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(302, {}) or use other options such as http.Ok ...
	// return Response(302, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConsumeMagicLink method not implemented")
}
