// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// VaultHandlerService is a service that implements the logic for the VaultHandlerServicer
// This service should implement the business logic for every endpoint for the VaultHandler API.
// Include any external packages or services that will be required by this service.
type VaultHandlerService struct {
}

// NewVaultHandlerService creates a default api service
func NewVaultHandlerService() *VaultHandlerService {
	return &VaultHandlerService{}
}

// GetVaults - 
func (s *VaultHandlerService) GetVaults(ctx context.Context, pageSize int32, pageIndex int32) (ImplResponse, error) {
	// TODO - update GetVaults with the required logic for this service method.
	// Add api_vault_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, VaultsResponse{}) or use other options such as http.Ok ...
	// return Response(200, VaultsResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetVaults method not implemented")
}

// CreateVault - 
func (s *VaultHandlerService) CreateVault(ctx context.Context, createVaultRequest CreateVaultRequest) (ImplResponse, error) {
	// TODO - update CreateVault with the required logic for this service method.
	// Add api_vault_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Vault{}) or use other options such as http.Ok ...
	// return Response(201, Vault{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateVault method not implemented")
}

// GetVault - 
func (s *VaultHandlerService) GetVault(ctx context.Context, uniqueId string) (ImplResponse, error) {
	// TODO - update GetVault with the required logic for this service method.
	// Add api_vault_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Vault{}) or use other options such as http.Ok ...
	// return Response(200, Vault{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetVault method not implemented")
}

// UpdateVault - 
func (s *VaultHandlerService) UpdateVault(ctx context.Context, uniqueId string, updateVaultRequest UpdateVaultRequest) (ImplResponse, error) {
	// TODO - update UpdateVault with the required logic for this service method.
	// Add api_vault_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Vault{}) or use other options such as http.Ok ...
	// return Response(200, Vault{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateVault method not implemented")
}

// DeleteVault - 
func (s *VaultHandlerService) DeleteVault(ctx context.Context, uniqueId string) (ImplResponse, error) {
	// TODO - update DeleteVault with the required logic for this service method.
	// Add api_vault_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteVault method not implemented")
}
