// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"net/http"
	"strings"
)

// DefaultHandlerController binds http requests to an api service and writes the service results to the http response
type DefaultHandlerController struct {
	service DefaultHandlerServicer
	errorHandler ErrorHandler
}

// DefaultHandlerOption for how the controller is set up.
type DefaultHandlerOption func(*DefaultHandlerController)

// WithDefaultHandlerErrorHandler inject ErrorHandler into controller
func WithDefaultHandlerErrorHandler(h ErrorHandler) DefaultHandlerOption {
	return func(c *DefaultHandlerController) {
		c.errorHandler = h
	}
}

// NewDefaultHandlerController creates a default api controller
func NewDefaultHandlerController(s DefaultHandlerServicer, opts ...DefaultHandlerOption) *DefaultHandlerController {
	controller := &DefaultHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultHandlerController
func (c *DefaultHandlerController) Routes() Routes {
	return Routes{
		"Health": Route{
			"Health",
			strings.ToUpper("Get"),
			"/api/health",
			c.Health,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the DefaultHandlerController
func (c *DefaultHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"Health",
			strings.ToUpper("Get"),
			"/api/health",
			c.Health,
		},
	}
}



// Health - 
func (c *DefaultHandlerController) Health(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Health(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
