// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// APIKeyHandlerService is a service that implements the logic for the APIKeyHandlerServicer
// This service should implement the business logic for every endpoint for the APIKeyHandler API.
// Include any external packages or services that will be required by this service.
type APIKeyHandlerService struct {
}

// NewAPIKeyHandlerService creates a default api service
func NewAPIKeyHandlerService() *APIKeyHandlerService {
	return &APIKeyHandlerService{}
}

// GetAPIKeys - 
func (s *APIKeyHandlerService) GetAPIKeys(ctx context.Context, pageSize int32, pageIndex int32) (ImplResponse, error) {
	// TODO - update GetAPIKeys with the required logic for this service method.
	// Add api_api_key_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ApiKeysResponse{}) or use other options such as http.Ok ...
	// return Response(200, ApiKeysResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAPIKeys method not implemented")
}

// CreateAPIKey - 
func (s *APIKeyHandlerService) CreateAPIKey(ctx context.Context, createApiKeyRequest CreateApiKeyRequest) (ImplResponse, error) {
	// TODO - update CreateAPIKey with the required logic for this service method.
	// Add api_api_key_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, CreateApiKeyResponse{}) or use other options such as http.Ok ...
	// return Response(201, CreateApiKeyResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateAPIKey method not implemented")
}

// DeleteAPIKey - 
func (s *APIKeyHandlerService) DeleteAPIKey(ctx context.Context, id int64) (ImplResponse, error) {
	// TODO - update DeleteAPIKey with the required logic for this service method.
	// Add api_api_key_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteAPIKey method not implemented")
}

// UpdateAPIKey - 
func (s *APIKeyHandlerService) UpdateAPIKey(ctx context.Context, id int64, updateApiKeyRequest UpdateApiKeyRequest) (ImplResponse, error) {
	// TODO - update UpdateAPIKey with the required logic for this service method.
	// Add api_api_key_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, VaultApiKey{}) or use other options such as http.Ok ...
	// return Response(200, VaultApiKey{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateAPIKey method not implemented")
}
