// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"encoding/json"
	"net/http"
	"strings"
)

// AuthHandlerController binds http requests to an api service and writes the service results to the http response
type AuthHandlerController struct {
	service AuthHandlerServicer
	errorHandler ErrorHandler
}

// AuthHandlerOption for how the controller is set up.
type AuthHandlerOption func(*AuthHandlerController)

// WithAuthHandlerErrorHandler inject ErrorHandler into controller
func WithAuthHandlerErrorHandler(h ErrorHandler) AuthHandlerOption {
	return func(c *AuthHandlerController) {
		c.errorHandler = h
	}
}

// NewAuthHandlerController creates a default api controller
func NewAuthHandlerController(s AuthHandlerServicer, opts ...AuthHandlerOption) *AuthHandlerController {
	controller := &AuthHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuthHandlerController
func (c *AuthHandlerController) Routes() Routes {
	return Routes{
		"Login": Route{
			"Login",
			strings.ToUpper("Post"),
			"/api/auth/login",
			c.Login,
		},
		"Signup": Route{
			"Signup",
			strings.ToUpper("Post"),
			"/api/auth/signup",
			c.Signup,
		},
		"Logout": Route{
			"Logout",
			strings.ToUpper("Get"),
			"/api/auth/logout",
			c.Logout,
		},
		"RequestPasswordReset": Route{
			"RequestPasswordReset",
			strings.ToUpper("Post"),
			"/api/auth/password/reset/request",
			c.RequestPasswordReset,
		},
		"ConfirmPasswordReset": Route{
			"ConfirmPasswordReset",
			strings.ToUpper("Post"),
			"/api/auth/password/reset/confirm",
			c.ConfirmPasswordReset,
		},
		"RequestMagicLink": Route{
			"RequestMagicLink",
			strings.ToUpper("Post"),
			"/api/auth/magic-link/request",
			c.RequestMagicLink,
		},
		"ConsumeMagicLink": Route{
			"ConsumeMagicLink",
			strings.ToUpper("Get"),
			"/api/auth/magic-link/token",
			c.ConsumeMagicLink,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the AuthHandlerController
func (c *AuthHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"Login",
			strings.ToUpper("Post"),
			"/api/auth/login",
			c.Login,
		},
		Route{
			"Signup",
			strings.ToUpper("Post"),
			"/api/auth/signup",
			c.Signup,
		},
		Route{
			"Logout",
			strings.ToUpper("Get"),
			"/api/auth/logout",
			c.Logout,
		},
		Route{
			"RequestPasswordReset",
			strings.ToUpper("Post"),
			"/api/auth/password/reset/request",
			c.RequestPasswordReset,
		},
		Route{
			"ConfirmPasswordReset",
			strings.ToUpper("Post"),
			"/api/auth/password/reset/confirm",
			c.ConfirmPasswordReset,
		},
		Route{
			"RequestMagicLink",
			strings.ToUpper("Post"),
			"/api/auth/magic-link/request",
			c.RequestMagicLink,
		},
		Route{
			"ConsumeMagicLink",
			strings.ToUpper("Get"),
			"/api/auth/magic-link/token",
			c.ConsumeMagicLink,
		},
	}
}



// Login - 
func (c *AuthHandlerController) Login(w http.ResponseWriter, r *http.Request) {
	var loginRequestParam LoginRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&loginRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertLoginRequestRequired(loginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertLoginRequestConstraints(loginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Login(r.Context(), loginRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// Signup - 
func (c *AuthHandlerController) Signup(w http.ResponseWriter, r *http.Request) {
	var signupRequestParam SignupRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&signupRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertSignupRequestRequired(signupRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertSignupRequestConstraints(signupRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Signup(r.Context(), signupRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// Logout - 
func (c *AuthHandlerController) Logout(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Logout(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RequestPasswordReset - 
func (c *AuthHandlerController) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	var passwordResetRequestParam PasswordResetRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&passwordResetRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPasswordResetRequestRequired(passwordResetRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPasswordResetRequestConstraints(passwordResetRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RequestPasswordReset(r.Context(), passwordResetRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConfirmPasswordReset - 
func (c *AuthHandlerController) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	var passwordResetConfirmRequestParam PasswordResetConfirmRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&passwordResetConfirmRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPasswordResetConfirmRequestRequired(passwordResetConfirmRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPasswordResetConfirmRequestConstraints(passwordResetConfirmRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ConfirmPasswordReset(r.Context(), passwordResetConfirmRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RequestMagicLink - 
func (c *AuthHandlerController) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	var magicLinkRequestParam MagicLinkRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&magicLinkRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertMagicLinkRequestRequired(magicLinkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertMagicLinkRequestConstraints(magicLinkRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RequestMagicLink(r.Context(), magicLinkRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ConsumeMagicLink - 
func (c *AuthHandlerController) ConsumeMagicLink(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var tokenParam string
	if query.Has("token") {
		param := query.Get("token")

		tokenParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "token"}, nil)
		return
	}
	result, err := c.service.ConsumeMagicLink(r.Context(), tokenParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
