// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// APIKeyHandlerController binds http requests to an api service and writes the service results to the http response
type APIKeyHandlerController struct {
	service APIKeyHandlerServicer
	errorHandler ErrorHandler
}

// APIKeyHandlerOption for how the controller is set up.
type APIKeyHandlerOption func(*APIKeyHandlerController)

// WithAPIKeyHandlerErrorHandler inject ErrorHandler into controller
func WithAPIKeyHandlerErrorHandler(h ErrorHandler) APIKeyHandlerOption {
	return func(c *APIKeyHandlerController) {
		c.errorHandler = h
	}
}

// NewAPIKeyHandlerController creates a default api controller
func NewAPIKeyHandlerController(s APIKeyHandlerServicer, opts ...APIKeyHandlerOption) *APIKeyHandlerController {
	controller := &APIKeyHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the APIKeyHandlerController
func (c *APIKeyHandlerController) Routes() Routes {
	return Routes{
		"GetAPIKeys": Route{
			"GetAPIKeys",
			strings.ToUpper("Get"),
			"/api/api-keys",
			c.GetAPIKeys,
		},
		"CreateAPIKey": Route{
			"CreateAPIKey",
			strings.ToUpper("Post"),
			"/api/api-keys",
			c.CreateAPIKey,
		},
		"DeleteAPIKey": Route{
			"DeleteAPIKey",
			strings.ToUpper("Delete"),
			"/api/api-keys/{id}",
			c.DeleteAPIKey,
		},
		"UpdateAPIKey": Route{
			"UpdateAPIKey",
			strings.ToUpper("Patch"),
			"/api/api-keys/{id}",
			c.UpdateAPIKey,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the APIKeyHandlerController
func (c *APIKeyHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetAPIKeys",
			strings.ToUpper("Get"),
			"/api/api-keys",
			c.GetAPIKeys,
		},
		Route{
			"CreateAPIKey",
			strings.ToUpper("Post"),
			"/api/api-keys",
			c.CreateAPIKey,
		},
		Route{
			"DeleteAPIKey",
			strings.ToUpper("Delete"),
			"/api/api-keys/{id}",
			c.DeleteAPIKey,
		},
		Route{
			"UpdateAPIKey",
			strings.ToUpper("Patch"),
			"/api/api-keys/{id}",
			c.UpdateAPIKey,
		},
	}
}



// GetAPIKeys - 
func (c *APIKeyHandlerController) GetAPIKeys(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var pageSizeParam int32
	if query.Has("pageSize") {
		param, err := parseNumericParameter[int32](
			query.Get("pageSize"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](1000),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "pageSize", Err: err}, nil)
			return
		}

		pageSizeParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "pageSize"}, nil)
		return
	}
	var pageIndexParam int32
	if query.Has("pageIndex") {
		param, err := parseNumericParameter[int32](
			query.Get("pageIndex"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "pageIndex", Err: err}, nil)
			return
		}

		pageIndexParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "pageIndex"}, nil)
		return
	}
	result, err := c.service.GetAPIKeys(r.Context(), pageSizeParam, pageIndexParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreateAPIKey - 
func (c *APIKeyHandlerController) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	var createApiKeyRequestParam CreateApiKeyRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&createApiKeyRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCreateApiKeyRequestRequired(createApiKeyRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertCreateApiKeyRequestConstraints(createApiKeyRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateAPIKey(r.Context(), createApiKeyRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteAPIKey - 
func (c *APIKeyHandlerController) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int64](
		params["id"],
		WithRequire[int64](parseInt64),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	result, err := c.service.DeleteAPIKey(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateAPIKey - 
func (c *APIKeyHandlerController) UpdateAPIKey(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int64](
		params["id"],
		WithRequire[int64](parseInt64),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	var updateApiKeyRequestParam UpdateApiKeyRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&updateApiKeyRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUpdateApiKeyRequestRequired(updateApiKeyRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUpdateApiKeyRequestConstraints(updateApiKeyRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateAPIKey(r.Context(), idParam, updateApiKeyRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
