// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// ConfigHandlerService is a service that implements the logic for the ConfigHandlerServicer
// This service should implement the business logic for every endpoint for the ConfigHandler API.
// Include any external packages or services that will be required by this service.
type ConfigHandlerService struct {
}

// NewConfigHandlerService creates a default api service
func NewConfigHandlerService() *ConfigHandlerService {
	return &ConfigHandlerService{}
}

// GetConfig - Get public configuration
func (s *ConfigHandlerService) GetConfig(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetConfig with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ConfigResponse{}) or use other options such as http.Ok ...
	// return Response(200, ConfigResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfig method not implemented")
}
