// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// CliHandlerController binds http requests to an api service and writes the service results to the http response
type CliHandlerController struct {
	service CliHandlerServicer
	errorHandler ErrorHandler
}

// CliHandlerOption for how the controller is set up.
type CliHandlerOption func(*CliHandlerController)

// WithCliHandlerErrorHandler inject ErrorHandler into controller
func WithCliHandlerErrorHandler(h ErrorHandler) CliHandlerOption {
	return func(c *CliHandlerController) {
		c.errorHandler = h
	}
}

// NewCliHandlerController creates a default api controller
func NewCliHandlerController(s CliHandlerServicer, opts ...CliHandlerOption) *CliHandlerController {
	controller := &CliHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the CliHandlerController
func (c *CliHandlerController) Routes() Routes {
	return Routes{
		"GetVaultsByAPIKey": Route{
			"GetVaultsByAPIKey",
			strings.ToUpper("Get"),
			"/api/cli/vaults",
			c.GetVaultsByAPIKey,
		},
		"GetVaultByAPIKey": Route{
			"GetVaultByAPIKey",
			strings.ToUpper("Get"),
			"/api/cli/vault/{uniqueId}",
			c.GetVaultByAPIKey,
		},
		"GetVaultByNameAPIKey": Route{
			"GetVaultByNameAPIKey",
			strings.ToUpper("Get"),
			"/api/cli/vault/name/{name}",
			c.GetVaultByNameAPIKey,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the CliHandlerController
func (c *CliHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetVaultsByAPIKey",
			strings.ToUpper("Get"),
			"/api/cli/vaults",
			c.GetVaultsByAPIKey,
		},
		Route{
			"GetVaultByAPIKey",
			strings.ToUpper("Get"),
			"/api/cli/vault/{uniqueId}",
			c.GetVaultByAPIKey,
		},
		Route{
			"GetVaultByNameAPIKey",
			strings.ToUpper("Get"),
			"/api/cli/vault/name/{name}",
			c.GetVaultByNameAPIKey,
		},
	}
}



// GetVaultsByAPIKey - 
func (c *CliHandlerController) GetVaultsByAPIKey(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetVaultsByAPIKey(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetVaultByAPIKey - 
func (c *CliHandlerController) GetVaultByAPIKey(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	uniqueIdParam := params["uniqueId"]
	if uniqueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"uniqueId"}, nil)
		return
	}
	xEnableClientEncryptionParam := r.Header.Get("X-Enable-Client-Encryption")
	result, err := c.service.GetVaultByAPIKey(r.Context(), uniqueIdParam, xEnableClientEncryptionParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetVaultByNameAPIKey - 
func (c *CliHandlerController) GetVaultByNameAPIKey(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nameParam := params["name"]
	if nameParam == "" {
		c.errorHandler(w, r, &RequiredError{"name"}, nil)
		return
	}
	xEnableClientEncryptionParam := r.Header.Get("X-Enable-Client-Encryption")
	result, err := c.service.GetVaultByNameAPIKey(r.Context(), nameParam, xEnableClientEncryptionParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
