// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// UserHandlerService is a service that implements the logic for the UserHandlerServicer
// This service should implement the business logic for every endpoint for the UserHandler API.
// Include any external packages or services that will be required by this service.
type UserHandlerService struct {
}

// NewUserHandlerService creates a default api service
func NewUserHandlerService() *UserHandlerService {
	return &UserHandlerService{}
}

// GetCurrentUser - 
func (s *UserHandlerService) GetCurrentUser(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetCurrentUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetUserResponse{}) or use other options such as http.Ok ...
	// return Response(200, GetUserResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCurrentUser method not implemented")
}
