// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"net/http"
	"strings"
	"time"
)

// AuditHandlerController binds http requests to an api service and writes the service results to the http response
type AuditHandlerController struct {
	service AuditHandlerServicer
	errorHandler ErrorHandler
}

// AuditHandlerOption for how the controller is set up.
type AuditHandlerOption func(*AuditHandlerController)

// WithAuditHandlerErrorHandler inject ErrorHandler into controller
func WithAuditHandlerErrorHandler(h ErrorHandler) AuditHandlerOption {
	return func(c *AuditHandlerController) {
		c.errorHandler = h
	}
}

// NewAuditHandlerController creates a default api controller
func NewAuditHandlerController(s AuditHandlerServicer, opts ...AuditHandlerOption) *AuditHandlerController {
	controller := &AuditHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuditHandlerController
func (c *AuditHandlerController) Routes() Routes {
	return Routes{
		"GetAuditLogs": Route{
			"GetAuditLogs",
			strings.ToUpper("Get"),
			"/api/audit-logs",
			c.GetAuditLogs,
		},
		"GetAuditMetrics": Route{
			"GetAuditMetrics",
			strings.ToUpper("Get"),
			"/api/audit-logs/metrics",
			c.GetAuditMetrics,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the AuditHandlerController
func (c *AuditHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetAuditLogs",
			strings.ToUpper("Get"),
			"/api/audit-logs",
			c.GetAuditLogs,
		},
		Route{
			"GetAuditMetrics",
			strings.ToUpper("Get"),
			"/api/audit-logs/metrics",
			c.GetAuditMetrics,
		},
	}
}



// GetAuditLogs - 
func (c *AuditHandlerController) GetAuditLogs(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var pageSizeParam int32
	if query.Has("pageSize") {
		param, err := parseNumericParameter[int32](
			query.Get("pageSize"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](1000),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "pageSize", Err: err}, nil)
			return
		}

		pageSizeParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "pageSize"}, nil)
		return
	}
	var pageIndexParam int32
	if query.Has("pageIndex") {
		param, err := parseNumericParameter[int32](
			query.Get("pageIndex"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "pageIndex", Err: err}, nil)
			return
		}

		pageIndexParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "pageIndex"}, nil)
		return
	}
	var startDateParam time.Time
	if query.Has("startDate"){
		param, err := parseTime(query.Get("startDate"))
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "startDate", Err: err}, nil)
			return
		}

		startDateParam = param
	} else {
	}
	var endDateParam time.Time
	if query.Has("endDate"){
		param, err := parseTime(query.Get("endDate"))
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "endDate", Err: err}, nil)
			return
		}

		endDateParam = param
	} else {
	}
	var vaultUniqueIdParam string
	if query.Has("vaultUniqueId") {
		param := query.Get("vaultUniqueId")

		vaultUniqueIdParam = param
	} else {
	}
	result, err := c.service.GetAuditLogs(r.Context(), pageSizeParam, pageIndexParam, startDateParam, endDateParam, vaultUniqueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAuditMetrics - 
func (c *AuditHandlerController) GetAuditMetrics(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetAuditMetrics(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
