// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
	"time"
)

// AuditHandlerService is a service that implements the logic for the AuditHandlerServicer
// This service should implement the business logic for every endpoint for the AuditHandler API.
// Include any external packages or services that will be required by this service.
type AuditHandlerService struct {
}

// NewAuditHandlerService creates a default api service
func NewAuditHandlerService() *AuditHandlerService {
	return &AuditHandlerService{}
}

// GetAuditLogs - 
func (s *AuditHandlerService) GetAuditLogs(ctx context.Context, pageSize int32, pageIndex int32, startDate time.Time, endDate time.Time, vaultUniqueId string) (ImplResponse, error) {
	// TODO - update GetAuditLogs with the required logic for this service method.
	// Add api_audit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AuditLogsResponse{}) or use other options such as http.Ok ...
	// return Response(200, AuditLogsResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAuditLogs method not implemented")
}

// GetAuditMetrics - 
func (s *AuditHandlerService) GetAuditMetrics(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetAuditMetrics with the required logic for this service method.
	// Add api_audit_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AuditMetricsResponse{}) or use other options such as http.Ok ...
	// return Response(200, AuditMetricsResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAuditMetrics method not implemented")
}
