// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// VaultHandlerController binds http requests to an api service and writes the service results to the http response
type VaultHandlerController struct {
	service VaultHandlerServicer
	errorHandler ErrorHandler
}

// VaultHandlerOption for how the controller is set up.
type VaultHandlerOption func(*VaultHandlerController)

// WithVaultHandlerErrorHandler inject ErrorHandler into controller
func WithVaultHandlerErrorHandler(h ErrorHandler) VaultHandlerOption {
	return func(c *VaultHandlerController) {
		c.errorHandler = h
	}
}

// NewVaultHandlerController creates a default api controller
func NewVaultHandlerController(s VaultHandlerServicer, opts ...VaultHandlerOption) *VaultHandlerController {
	controller := &VaultHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the VaultHandlerController
func (c *VaultHandlerController) Routes() Routes {
	return Routes{
		"GetVaults": Route{
			"GetVaults",
			strings.ToUpper("Get"),
			"/api/vaults",
			c.GetVaults,
		},
		"CreateVault": Route{
			"CreateVault",
			strings.ToUpper("Post"),
			"/api/vaults",
			c.CreateVault,
		},
		"GetVault": Route{
			"GetVault",
			strings.ToUpper("Get"),
			"/api/vaults/{uniqueId}",
			c.GetVault,
		},
		"UpdateVault": Route{
			"UpdateVault",
			strings.ToUpper("Put"),
			"/api/vaults/{uniqueId}",
			c.UpdateVault,
		},
		"DeleteVault": Route{
			"DeleteVault",
			strings.ToUpper("Delete"),
			"/api/vaults/{uniqueId}",
			c.DeleteVault,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the VaultHandlerController
func (c *VaultHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetVaults",
			strings.ToUpper("Get"),
			"/api/vaults",
			c.GetVaults,
		},
		Route{
			"CreateVault",
			strings.ToUpper("Post"),
			"/api/vaults",
			c.CreateVault,
		},
		Route{
			"GetVault",
			strings.ToUpper("Get"),
			"/api/vaults/{uniqueId}",
			c.GetVault,
		},
		Route{
			"UpdateVault",
			strings.ToUpper("Put"),
			"/api/vaults/{uniqueId}",
			c.UpdateVault,
		},
		Route{
			"DeleteVault",
			strings.ToUpper("Delete"),
			"/api/vaults/{uniqueId}",
			c.DeleteVault,
		},
	}
}



// GetVaults - 
func (c *VaultHandlerController) GetVaults(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var pageSizeParam int32
	if query.Has("pageSize") {
		param, err := parseNumericParameter[int32](
			query.Get("pageSize"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](1000),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "pageSize", Err: err}, nil)
			return
		}

		pageSizeParam = param
	} else {
		var param int32 = 20
		pageSizeParam = param
	}
	var pageIndexParam int32
	if query.Has("pageIndex") {
		param, err := parseNumericParameter[int32](
			query.Get("pageIndex"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "pageIndex", Err: err}, nil)
			return
		}

		pageIndexParam = param
	} else {
		var param int32 = 1
		pageIndexParam = param
	}
	result, err := c.service.GetVaults(r.Context(), pageSizeParam, pageIndexParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreateVault - 
func (c *VaultHandlerController) CreateVault(w http.ResponseWriter, r *http.Request) {
	var createVaultRequestParam CreateVaultRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&createVaultRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCreateVaultRequestRequired(createVaultRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertCreateVaultRequestConstraints(createVaultRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateVault(r.Context(), createVaultRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetVault - 
func (c *VaultHandlerController) GetVault(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	uniqueIdParam := params["uniqueId"]
	if uniqueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"uniqueId"}, nil)
		return
	}
	result, err := c.service.GetVault(r.Context(), uniqueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateVault - 
func (c *VaultHandlerController) UpdateVault(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	uniqueIdParam := params["uniqueId"]
	if uniqueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"uniqueId"}, nil)
		return
	}
	var updateVaultRequestParam UpdateVaultRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&updateVaultRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUpdateVaultRequestRequired(updateVaultRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUpdateVaultRequestConstraints(updateVaultRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateVault(r.Context(), uniqueIdParam, updateVaultRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteVault - 
func (c *VaultHandlerController) DeleteVault(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	uniqueIdParam := params["uniqueId"]
	if uniqueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"uniqueId"}, nil)
		return
	}
	result, err := c.service.DeleteVault(r.Context(), uniqueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
