// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"context"
	"net/http"
	"errors"
)

// DefaultHandlerService is a service that implements the logic for the DefaultHandlerServicer
// This service should implement the business logic for every endpoint for the DefaultHandler API.
// Include any external packages or services that will be required by this service.
type DefaultHandlerService struct {
}

// NewDefaultHandlerService creates a default api service
func NewDefaultHandlerService() *DefaultHandlerService {
	return &DefaultHandlerService{}
}

// Health - 
func (s *DefaultHandlerService) Health(ctx context.Context) (ImplResponse, error) {
	// TODO - update Health with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, HealthCheckResponse{}) or use other options such as http.Ok ...
	// return Response(200, HealthCheckResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Health method not implemented")
}
