// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv

import (
	"net/http"
	"strings"
)

// UserHandlerController binds http requests to an api service and writes the service results to the http response
type UserHandlerController struct {
	service UserHandlerServicer
	errorHandler ErrorHandler
}

// UserHandlerOption for how the controller is set up.
type UserHandlerOption func(*UserHandlerController)

// WithUserHandlerErrorHandler inject ErrorHandler into controller
func WithUserHandlerErrorHandler(h ErrorHandler) UserHandlerOption {
	return func(c *UserHandlerController) {
		c.errorHandler = h
	}
}

// NewUserHandlerController creates a default api controller
func NewUserHandlerController(s UserHandlerServicer, opts ...UserHandlerOption) *UserHandlerController {
	controller := &UserHandlerController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the UserHandlerController
func (c *UserHandlerController) Routes() Routes {
	return Routes{
		"GetCurrentUser": Route{
			"GetCurrentUser",
			strings.ToUpper("Get"),
			"/api/user",
			c.GetCurrentUser,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the UserHandlerController
func (c *UserHandlerController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetCurrentUser",
			strings.ToUpper("Get"),
			"/api/user",
			c.GetCurrentUser,
		},
	}
}



// GetCurrentUser - 
func (c *UserHandlerController) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetCurrentUser(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
