// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type UpdateApiKeyRequest struct {

	// Human-readable name for the API key
	Name string `json:"name,omitempty"`

	// Array of vault unique IDs this key can access (empty = all user's vaults)
	VaultUniqueIds []string `json:"vaultUniqueIds,omitempty"`

	// Optional expiration date
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}

// AssertUpdateApiKeyRequestRequired checks if the required fields are not zero-ed
func AssertUpdateApiKeyRequestRequired(obj UpdateApiKeyRequest) error {
	return nil
}

// AssertUpdateApiKeyRequestConstraints checks if the values respects the defined constraints
func AssertUpdateApiKeyRequestConstraints(obj UpdateApiKeyRequest) error {
	return nil
}
