// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type HealthCheckResponse struct {

	Status string `json:"status,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}

// AssertHealthCheckResponseRequired checks if the required fields are not zero-ed
func AssertHealthCheckResponseRequired(obj HealthCheckResponse) error {
	return nil
}

// AssertHealthCheckResponseConstraints checks if the values respects the defined constraints
func AssertHealthCheckResponseConstraints(obj HealthCheckResponse) error {
	return nil
}
