// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"fmt"
)


// EnableClientEncryption : Enable additional client-side encryption using key derived from API key + vault unique ID
type EnableClientEncryption string

// List of EnableClientEncryption
const (
	TRUE EnableClientEncryption = "true"
	FALSE EnableClientEncryption = "false"
)

// AllowedEnableClientEncryptionEnumValues is all the allowed values of EnableClientEncryption enum
var AllowedEnableClientEncryptionEnumValues = []EnableClientEncryption{
	"true",
	"false",
}

// validEnableClientEncryptionEnumValue provides a map of EnableClientEncryptions for fast verification of use input
var validEnableClientEncryptionEnumValues = map[EnableClientEncryption]struct{}{
	"true": {},
	"false": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnableClientEncryption) IsValid() bool {
	_, ok := validEnableClientEncryptionEnumValues[v]
	return ok
}

// NewEnableClientEncryptionFromValue returns a pointer to a valid EnableClientEncryption
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnableClientEncryptionFromValue(v string) (EnableClientEncryption, error) {
	ev := EnableClientEncryption(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for EnableClientEncryption: valid values are %v", v, AllowedEnableClientEncryptionEnumValues)
}



// AssertEnableClientEncryptionRequired checks if the required fields are not zero-ed
func AssertEnableClientEncryptionRequired(obj EnableClientEncryption) error {
	return nil
}

// AssertEnableClientEncryptionConstraints checks if the values respects the defined constraints
func AssertEnableClientEncryptionConstraints(obj EnableClientEncryption) error {
	return nil
}
