// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type AuditMetricsResponse struct {

	// Total number of audit events in the last 30 days
	TotalEventsLast30Days int32 `json:"totalEventsLast30Days"`

	// Number of audit events in the last 24 hours
	EventsCountLast24Hours int32 `json:"eventsCountLast24Hours"`

	// Number of vault-related events in the last 30 days
	VaultEventsLast30Days int32 `json:"vaultEventsLast30Days"`

	// Number of API key-related events in the last 30 days
	ApiKeyEventsLast30Days int32 `json:"apiKeyEventsLast30Days"`
}

// AssertAuditMetricsResponseRequired checks if the required fields are not zero-ed
func AssertAuditMetricsResponseRequired(obj AuditMetricsResponse) error {
	elements := map[string]interface{}{
		"totalEventsLast30Days": obj.TotalEventsLast30Days,
		"eventsCountLast24Hours": obj.EventsCountLast24Hours,
		"vaultEventsLast30Days": obj.VaultEventsLast30Days,
		"apiKeyEventsLast30Days": obj.ApiKeyEventsLast30Days,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAuditMetricsResponseConstraints checks if the values respects the defined constraints
func AssertAuditMetricsResponseConstraints(obj AuditMetricsResponse) error {
	return nil
}
