// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type VaultsResponse struct {

	// Page of vault records for the authenticated user
	Vaults []VaultLite `json:"vaults"`

	// Total number of vaults available for pagination
	TotalCount int32 `json:"totalCount"`

	// Number of vaults returned per page
	PageSize int32 `json:"pageSize"`

	// Current page index (starting from 1)
	PageIndex int32 `json:"pageIndex"`
}

// AssertVaultsResponseRequired checks if the required fields are not zero-ed
func AssertVaultsResponseRequired(obj VaultsResponse) error {
	elements := map[string]interface{}{
		"vaults": obj.Vaults,
		"totalCount": obj.TotalCount,
		"pageSize": obj.PageSize,
		"pageIndex": obj.PageIndex,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Vaults {
		if err := AssertVaultLiteRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertVaultsResponseConstraints checks if the values respects the defined constraints
func AssertVaultsResponseConstraints(obj VaultsResponse) error {
	for _, el := range obj.Vaults {
		if err := AssertVaultLiteConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
