// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type VaultLite struct {

	// Unique identifier for the vault
	UniqueId string `json:"uniqueId"`

	// Human-readable name
	Name string `json:"name"`

	// Human-readable description
	Description string `json:"description,omitempty"`

	// Category/type of vault
	Category string `json:"category,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertVaultLiteRequired checks if the required fields are not zero-ed
func AssertVaultLiteRequired(obj VaultLite) error {
	elements := map[string]interface{}{
		"uniqueId": obj.UniqueId,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertVaultLiteConstraints checks if the values respects the defined constraints
func AssertVaultLiteConstraints(obj VaultLite) error {
	return nil
}
