// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type MagicLinkRequest struct {

	Email string `json:"email"`
}

// AssertMagicLinkRequestRequired checks if the required fields are not zero-ed
func AssertMagicLinkRequestRequired(obj MagicLinkRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMagicLinkRequestConstraints checks if the values respects the defined constraints
func AssertMagicLinkRequestConstraints(obj MagicLinkRequest) error {
	return nil
}
