// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type ApiKeysResponse struct {

	ApiKeys []VaultApiKey `json:"apiKeys"`

	// Total number of API keys
	TotalCount int32 `json:"totalCount"`

	// Number of API keys per page
	PageSize int32 `json:"pageSize"`

	// Current page index (starting from 1)
	PageIndex int32 `json:"pageIndex"`
}

// AssertApiKeysResponseRequired checks if the required fields are not zero-ed
func AssertApiKeysResponseRequired(obj ApiKeysResponse) error {
	elements := map[string]interface{}{
		"apiKeys": obj.ApiKeys,
		"totalCount": obj.TotalCount,
		"pageSize": obj.PageSize,
		"pageIndex": obj.PageIndex,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.ApiKeys {
		if err := AssertVaultApiKeyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertApiKeysResponseConstraints checks if the values respects the defined constraints
func AssertApiKeysResponseConstraints(obj ApiKeysResponse) error {
	for _, el := range obj.ApiKeys {
		if err := AssertVaultApiKeyConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
