// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type AuditLog struct {

	// When the action occurred
	CreatedAt time.Time `json:"createdAt"`

	Vault VaultLite `json:"vault,omitempty"`

	ApiKey VaultApiKey `json:"apiKey,omitempty"`

	// Type of action performed
	Action string `json:"action"`

	// Source of the request (web interface or CLI)
	Source string `json:"source"`

	// IP address from which the action was performed
	IpAddress string `json:"ipAddress,omitempty"`

	// User agent string from the client
	UserAgent string `json:"userAgent,omitempty"`
}

// AssertAuditLogRequired checks if the required fields are not zero-ed
func AssertAuditLogRequired(obj AuditLog) error {
	elements := map[string]interface{}{
		"createdAt": obj.CreatedAt,
		"action": obj.Action,
		"source": obj.Source,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertVaultLiteRequired(obj.Vault); err != nil {
		return err
	}
	if err := AssertVaultApiKeyRequired(obj.ApiKey); err != nil {
		return err
	}
	return nil
}

// AssertAuditLogConstraints checks if the values respects the defined constraints
func AssertAuditLogConstraints(obj AuditLog) error {
	if err := AssertVaultLiteConstraints(obj.Vault); err != nil {
		return err
	}
	if err := AssertVaultApiKeyConstraints(obj.ApiKey); err != nil {
		return err
	}
	return nil
}
