// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type VaultApiKey struct {

	// Unique API key ID
	Id int64 `json:"id"`

	// Human-readable name for the API key
	Name string `json:"name"`

	// Array of vaults this key can access (null/empty = all user's vaults)
	Vaults []VaultLite `json:"vaults,omitempty"`

	// Optional expiration date
	ExpiresAt time.Time `json:"expiresAt,omitempty"`

	// When the key was last used
	LastUsedAt time.Time `json:"lastUsedAt,omitempty"`

	// Whether the key is currently active
	IsActive bool `json:"isActive"`

	// When the key was created
	CreatedAt time.Time `json:"createdAt"`

	// When the key was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertVaultApiKeyRequired checks if the required fields are not zero-ed
func AssertVaultApiKeyRequired(obj VaultApiKey) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"name": obj.Name,
		"isActive": obj.IsActive,
		"createdAt": obj.CreatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Vaults {
		if err := AssertVaultLiteRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertVaultApiKeyConstraints checks if the values respects the defined constraints
func AssertVaultApiKeyConstraints(obj VaultApiKey) error {
	for _, el := range obj.Vaults {
		if err := AssertVaultLiteConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
