// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type CreateVaultRequest struct {

	// Human-readable name
	Name string `json:"name"`

	// Value to be encrypted and stored
	Value string `json:"value"`

	// Human-readable description
	Description string `json:"description,omitempty"`

	// Category/type of vault
	Category string `json:"category,omitempty"`
}

// AssertCreateVaultRequestRequired checks if the required fields are not zero-ed
func AssertCreateVaultRequestRequired(obj CreateVaultRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateVaultRequestConstraints checks if the values respects the defined constraints
func AssertCreateVaultRequestConstraints(obj CreateVaultRequest) error {
	return nil
}
