// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type Vault struct {

	// Unique identifier for the vault
	UniqueId string `json:"uniqueId"`

	// ID of the user who owns this vault
	UserId int64 `json:"userId,omitempty"`

	// Human-readable name
	Name string `json:"name"`

	// Encrypted value
	Value string `json:"value"`

	// Human-readable description
	Description string `json:"description,omitempty"`

	// Category/type of vault
	Category string `json:"category,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertVaultRequired checks if the required fields are not zero-ed
func AssertVaultRequired(obj Vault) error {
	elements := map[string]interface{}{
		"uniqueId": obj.UniqueId,
		"name": obj.Name,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertVaultConstraints checks if the values respects the defined constraints
func AssertVaultConstraints(obj Vault) error {
	return nil
}
