// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv


import (
	"time"
)



type CreateApiKeyRequest struct {

	// Human-readable name for the API key
	Name string `json:"name"`

	// Array of vault unique IDs this key can access (empty = all user's vaults)
	VaultUniqueIds []string `json:"vaultUniqueIds,omitempty"`

	// Optional expiration date
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}

// AssertCreateApiKeyRequestRequired checks if the required fields are not zero-ed
func AssertCreateApiKeyRequestRequired(obj CreateApiKeyRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateApiKeyRequestConstraints checks if the values respects the defined constraints
func AssertCreateApiKeyRequestConstraints(obj CreateApiKeyRequest) error {
	return nil
}
