// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type EmailTokenResponse struct {

	// Indicates whether the email token request was accepted
	Success bool `json:"success"`

	// Machine-readable status code describing the outcome
	Code string `json:"code"`
}

// AssertEmailTokenResponseRequired checks if the required fields are not zero-ed
func AssertEmailTokenResponseRequired(obj EmailTokenResponse) error {
	elements := map[string]interface{}{
		"success": obj.Success,
		"code": obj.Code,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEmailTokenResponseConstraints checks if the values respects the defined constraints
func AssertEmailTokenResponseConstraints(obj EmailTokenResponse) error {
	return nil
}
