// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type UpdateVaultRequest struct {

	// Human-readable name
	Name string `json:"name,omitempty"`

	// Value to be encrypted and stored
	Value string `json:"value,omitempty"`

	// Human-readable description
	Description string `json:"description,omitempty"`

	// Category/type of vault
	Category string `json:"category,omitempty"`
}

// AssertUpdateVaultRequestRequired checks if the required fields are not zero-ed
func AssertUpdateVaultRequestRequired(obj UpdateVaultRequest) error {
	return nil
}

// AssertUpdateVaultRequestConstraints checks if the values respects the defined constraints
func AssertUpdateVaultRequestConstraints(obj UpdateVaultRequest) error {
	return nil
}
