// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type ConfigResponse struct {

	// Whether OIDC authentication is enabled
	OidcEnabled bool `json:"oidcEnabled"`

	// Whether transactional email is enabled
	EmailEnabled bool `json:"emailEnabled"`
}

// AssertConfigResponseRequired checks if the required fields are not zero-ed
func AssertConfigResponseRequired(obj ConfigResponse) error {
	elements := map[string]interface{}{
		"oidcEnabled": obj.OidcEnabled,
		"emailEnabled": obj.EmailEnabled,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertConfigResponseConstraints checks if the values respects the defined constraints
func AssertConfigResponseConstraints(obj ConfigResponse) error {
	return nil
}
