// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type SignupRequest struct {

	Email string `json:"email"`

	Password string `json:"password"`

	Name string `json:"name"`
}

// AssertSignupRequestRequired checks if the required fields are not zero-ed
func AssertSignupRequestRequired(obj SignupRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"password": obj.Password,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSignupRequestConstraints checks if the values respects the defined constraints
func AssertSignupRequestConstraints(obj SignupRequest) error {
	return nil
}
