// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type CreateApiKeyResponse struct {

	ApiKey VaultApiKey `json:"apiKey"`

	// The generated API key (only shown once)
	Key string `json:"key"`
}

// AssertCreateApiKeyResponseRequired checks if the required fields are not zero-ed
func AssertCreateApiKeyResponseRequired(obj CreateApiKeyResponse) error {
	elements := map[string]interface{}{
		"apiKey": obj.ApiKey,
		"key": obj.Key,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertVaultApiKeyRequired(obj.ApiKey); err != nil {
		return err
	}
	return nil
}

// AssertCreateApiKeyResponseConstraints checks if the values respects the defined constraints
func AssertCreateApiKeyResponseConstraints(obj CreateApiKeyResponse) error {
	if err := AssertVaultApiKeyConstraints(obj.ApiKey); err != nil {
		return err
	}
	return nil
}
