// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type PasswordResetConfirmRequest struct {

	Token string `json:"token"`

	NewPassword string `json:"newPassword"`
}

// AssertPasswordResetConfirmRequestRequired checks if the required fields are not zero-ed
func AssertPasswordResetConfirmRequestRequired(obj PasswordResetConfirmRequest) error {
	elements := map[string]interface{}{
		"token": obj.Token,
		"newPassword": obj.NewPassword,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPasswordResetConfirmRequestConstraints checks if the values respects the defined constraints
func AssertPasswordResetConfirmRequestConstraints(obj PasswordResetConfirmRequest) error {
	return nil
}
