// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type AuditLogsResponse struct {

	AuditLogs []AuditLog `json:"auditLogs"`

	// Total number of logs matching the filter criteria
	TotalCount int32 `json:"totalCount"`

	// Number of logs per page
	PageSize int32 `json:"pageSize"`

	// Current page index (starting from 0)
	PageIndex int32 `json:"pageIndex"`
}

// AssertAuditLogsResponseRequired checks if the required fields are not zero-ed
func AssertAuditLogsResponseRequired(obj AuditLogsResponse) error {
	elements := map[string]interface{}{
		"auditLogs": obj.AuditLogs,
		"totalCount": obj.TotalCount,
		"pageSize": obj.PageSize,
		"pageIndex": obj.PageIndex,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.AuditLogs {
		if err := AssertAuditLogRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAuditLogsResponseConstraints checks if the values respects the defined constraints
func AssertAuditLogsResponseConstraints(obj AuditLogsResponse) error {
	for _, el := range obj.AuditLogs {
		if err := AssertAuditLogConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
