// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Vault Hub Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.6
 */

package openapisrv




type StatusResponse struct {

	// Application version
	Version string `json:"version"`

	// Git commit hash
	Commit string `json:"commit"`

	// System operational status
	SystemStatus string `json:"systemStatus"`

	// Database connection status
	DatabaseStatus string `json:"databaseStatus"`
}

// AssertStatusResponseRequired checks if the required fields are not zero-ed
func AssertStatusResponseRequired(obj StatusResponse) error {
	elements := map[string]interface{}{
		"version": obj.Version,
		"commit": obj.Commit,
		"systemStatus": obj.SystemStatus,
		"databaseStatus": obj.DatabaseStatus,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertStatusResponseConstraints checks if the values respects the defined constraints
func AssertStatusResponseConstraints(obj StatusResponse) error {
	return nil
}
