openapi: 3.0.0
info:
  version: 1.1.0
  title: Vault Hub Server
# Merge path definitions from separate files
paths:
  # Health endpoints
  /api/health:
    $ref: ./paths/health.yaml#/health
  # Config endpoints
  /api/config:
    $ref: ./paths/config.yaml#/config
  # Status endpoints
  /api/status:
    $ref: ./paths/status.yaml#/status
  # Auth endpoints
  /api/auth/login:
    $ref: ./paths/auth.yaml#/login
  /api/auth/signup:
    $ref: ./paths/auth.yaml#/signup
  /api/auth/logout:
    $ref: ./paths/auth.yaml#/logout
  # Email-based auth endpoints
  /api/auth/request-password-reset:
    $ref: ./paths/email.yaml#/requestPasswordReset
  /api/auth/reset-password:
    $ref: ./paths/email.yaml#/resetPassword
  /api/auth/request-magic-link:
    $ref: ./paths/email.yaml#/requestMagicLink
  /api/auth/verify-email:
    $ref: ./paths/email.yaml#/verifyEmail
  /api/auth/resend-verification:
    $ref: ./paths/email.yaml#/resendVerification
  /api/auth/magic-link-callback:
    $ref: ./paths/email.yaml#/magicLinkCallback
  # User endpoints
  /api/user:
    $ref: ./paths/user.yaml#/getCurrentUser
  # Vault endpoints
  /api/vaults:
    $ref: ./paths/vault.yaml#/vaults
  /api/vaults/{uniqueId}:
    $ref: ./paths/vault.yaml#/vaultById
  # Audit endpoints
  /api/audit-logs:
    $ref: ./paths/audit.yaml#/auditLogs
  /api/audit-logs/metrics:
    $ref: ./paths/audit.yaml#/auditMetrics
  # API Key endpoints
  /api/api-keys:
    $ref: ./paths/apikey.yaml#/apiKeys
  /api/api-keys/{id}:
    $ref: ./paths/apikey.yaml#/apiKeyById
  /api/cli/vaults:
    $ref: ./paths/apikey-vault.yaml#/apiKeyVaults
  /api/cli/vault/{uniqueId}:
    $ref: ./paths/apikey-vault.yaml#/apiKeyVaultById
  /api/cli/vault/name/{name}:
    $ref: ./paths/apikey-vault.yaml#/apiKeyVaultByName
components:
  securitySchemes:
    apiKeyAuth:
      type: http
      scheme: bearer
  schemas:
    EnableClientEncryption:
      type: string
      description: Enable additional client-side encryption using key derived from API key + vault unique ID
      enum:
        - true
        - false
      example: true
    # Health schemas
    HealthCheckResponse:
      $ref: ./schemas/health.yaml#/HealthCheckResponse
    # Auth schemas
    LoginRequest:
      $ref: ./schemas/auth.yaml#/LoginRequest
    LoginResponse:
      $ref: ./schemas/auth.yaml#/LoginResponse
    SignupRequest:
      $ref: ./schemas/auth.yaml#/SignupRequest
    SignupResponse:
      $ref: ./schemas/auth.yaml#/SignupResponse
    # User schemas
    GetUserResponse:
      $ref: ./schemas/user.yaml#/GetUserResponse
    # Vault schemas
    VaultLite:
      $ref: ./schemas/vault.yaml#/VaultLite
    Vault:
      $ref: ./schemas/vault.yaml#/Vault
    CreateVaultRequest:
      $ref: ./schemas/vault.yaml#/CreateVaultRequest
    UpdateVaultRequest:
      $ref: ./schemas/vault.yaml#/UpdateVaultRequest
    # Audit log schemas
    AuditLogsResponse:
      $ref: ./schemas/audit.yaml#/AuditLogsResponse
    AuditLog:
      $ref: ./schemas/audit.yaml#/AuditLog
    AuditMetricsResponse:
      $ref: ./schemas/audit.yaml#/AuditMetricsResponse
    # API Key schemas
    APIKeysResponse:
      $ref: ./schemas/apikey.yaml#/APIKeysResponse
    VaultAPIKey:
      $ref: ./schemas/apikey.yaml#/VaultAPIKey
    CreateAPIKeyRequest:
      $ref: ./schemas/apikey.yaml#/CreateAPIKeyRequest
    CreateAPIKeyResponse:
      $ref: ./schemas/apikey.yaml#/CreateAPIKeyResponse
    UpdateAPIKeyRequest:
      $ref: ./schemas/apikey.yaml#/UpdateAPIKeyRequest
    # Status schemas
    StatusResponse:
      $ref: ./schemas/status.yaml#/StatusResponse
    # Config schemas
    ConfigResponse:
      $ref: ./schemas/config.yaml#/ConfigResponse
    # Email schemas
    RequestPasswordResetRequest:
      $ref: ./schemas/email.yaml#/RequestPasswordResetRequest
    RequestPasswordResetResponse:
      $ref: ./schemas/email.yaml#/RequestPasswordResetResponse
    ResetPasswordRequest:
      $ref: ./schemas/email.yaml#/ResetPasswordRequest
    ResetPasswordResponse:
      $ref: ./schemas/email.yaml#/ResetPasswordResponse
    RequestMagicLinkRequest:
      $ref: ./schemas/email.yaml#/RequestMagicLinkRequest
    RequestMagicLinkResponse:
      $ref: ./schemas/email.yaml#/RequestMagicLinkResponse
    VerifyEmailResponse:
      $ref: ./schemas/email.yaml#/VerifyEmailResponse
    ResendVerificationResponse:
      $ref: ./schemas/email.yaml#/ResendVerificationResponse
    MagicLinkCallbackResponse:
      $ref: ./schemas/email.yaml#/MagicLinkCallbackResponse
