openapi: 3.0.0
info:
  version: 1.0.10
  title: Vault Hub Server
# Merge path definitions from separate files
paths:
  # Health endpoints
  /api/health:
    $ref: ./paths/health.yaml#/health
  # Config endpoints
  /api/config:
    $ref: ./paths/config.yaml#/config
  # Status endpoints
  /api/status:
    $ref: ./paths/status.yaml#/status
  # Auth endpoints
  /api/auth/login:
    $ref: ./paths/auth.yaml#/login
  /api/auth/signup:
    $ref: ./paths/auth.yaml#/signup
  /api/auth/logout:
    $ref: ./paths/auth.yaml#/logout
  /api/auth/password/reset/request:
    $ref: ./paths/auth.yaml#/passwordResetRequest
  /api/auth/password/reset/confirm:
    $ref: ./paths/auth.yaml#/passwordResetConfirm
  /api/auth/magic-link/request:
    $ref: ./paths/auth.yaml#/magicLinkRequest
  /api/auth/magic-link/token:
    $ref: ./paths/auth.yaml#/magicLinkConsume
  /api/auth/password/change:
    $ref: ./paths/auth.yaml#/changePassword
  # User endpoints
  /api/user:
    $ref: ./paths/user.yaml#/getCurrentUser
  # Vault endpoints
  /api/vaults:
    $ref: ./paths/vault.yaml#/vaults
  /api/vaults/filter-options:
    $ref: ./paths/vault.yaml#/vaultFilterOptions
  /api/vaults/{uniqueId}:
    $ref: ./paths/vault.yaml#/vaultById
  # Audit endpoints
  /api/audit-logs:
    $ref: ./paths/audit.yaml#/auditLogs
  /api/audit-logs/metrics:
    $ref: ./paths/audit.yaml#/auditMetrics
  # API Key endpoints
  /api/api-keys:
    $ref: ./paths/apikey.yaml#/apiKeys
  /api/api-keys/{id}:
    $ref: ./paths/apikey.yaml#/apiKeyById
  /api/cli/vaults:
    $ref: ./paths/apikey-vault.yaml#/apiKeyVaults
  /api/cli/vault/{uniqueId}:
    $ref: ./paths/apikey-vault.yaml#/apiKeyVaultById
  /api/cli/vault/name/{name}:
    $ref: ./paths/apikey-vault.yaml#/apiKeyVaultByName
components:
  securitySchemes:
    apiKeyAuth:
      type: http
      scheme: bearer
  schemas:
    EnableClientEncryption:
      type: string
      description: Enable additional client-side encryption using key derived from API key + vault unique ID
      enum:
        - true
        - false
      example: true
    # Health schemas
    HealthCheckResponse:
      $ref: ./schemas/health.yaml#/HealthCheckResponse
    # Auth schemas
    LoginRequest:
      $ref: ./schemas/auth.yaml#/LoginRequest
    LoginResponse:
      $ref: ./schemas/auth.yaml#/LoginResponse
    SignupRequest:
      $ref: ./schemas/auth.yaml#/SignupRequest
    SignupResponse:
      $ref: ./schemas/auth.yaml#/SignupResponse
    PasswordResetRequest:
      $ref: ./schemas/auth.yaml#/PasswordResetRequest
    PasswordResetConfirmRequest:
      $ref: ./schemas/auth.yaml#/PasswordResetConfirmRequest
    MagicLinkRequest:
      $ref: ./schemas/auth.yaml#/MagicLinkRequest
    EmailTokenResponse:
      $ref: ./schemas/auth.yaml#/EmailTokenResponse
    ChangePasswordRequest:
      $ref: ./schemas/auth.yaml#/ChangePasswordRequest
    # User schemas
    GetUserResponse:
      $ref: ./schemas/user.yaml#/GetUserResponse
    # Vault schemas
    VaultLite:
      $ref: ./schemas/vault.yaml#/VaultLite
    Vault:
      $ref: ./schemas/vault.yaml#/Vault
    CreateVaultRequest:
      $ref: ./schemas/vault.yaml#/CreateVaultRequest
    UpdateVaultRequest:
      $ref: ./schemas/vault.yaml#/UpdateVaultRequest
    VaultFilterOption:
      $ref: ./schemas/vault.yaml#/VaultFilterOption
    VaultFilterOptionsResponse:
      $ref: ./schemas/vault.yaml#/VaultFilterOptionsResponse
    # Audit log schemas
    AuditLogsResponse:
      $ref: ./schemas/audit.yaml#/AuditLogsResponse
    AuditLog:
      $ref: ./schemas/audit.yaml#/AuditLog
    AuditMetricsResponse:
      $ref: ./schemas/audit.yaml#/AuditMetricsResponse
    # API Key schemas
    APIKeysResponse:
      $ref: ./schemas/apikey.yaml#/APIKeysResponse
    VaultAPIKey:
      $ref: ./schemas/apikey.yaml#/VaultAPIKey
    CreateAPIKeyRequest:
      $ref: ./schemas/apikey.yaml#/CreateAPIKeyRequest
    CreateAPIKeyResponse:
      $ref: ./schemas/apikey.yaml#/CreateAPIKeyResponse
    UpdateAPIKeyRequest:
      $ref: ./schemas/apikey.yaml#/UpdateAPIKeyRequest
    # Status schemas
    StatusResponse:
      $ref: ./schemas/status.yaml#/StatusResponse
    # Config schemas
    ConfigResponse:
      $ref: ./schemas/config.yaml#/ConfigResponse
