openapi: 3.0.0
info:
  version: 1.0.0
  title: Minimal ping API server
paths:
  /api/health:
    get:
      description: Check the health status of backend
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'

components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
          example: "ok"
        timestamp:
          type: string
          format: date-time
          example: "2023-10-11T12:34:56Z"
