// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v2"
	externalRef0 "github.com/lwshen/vault-hub/api"
	"github.com/oapi-codegen/runtime"
)

// APIKey defines model for APIKey.
type APIKey = externalRef0.APIKey

// APIKeysResponse defines model for APIKeysResponse.
type APIKeysResponse = externalRef0.APIKeysResponse

// AuditLogsResponse defines model for AuditLogsResponse.
type AuditLogsResponse = externalRef0.AuditLogsResponse

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest = externalRef0.CreateAPIKeyRequest

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse = externalRef0.CreateAPIKeyResponse

// CreateVaultRequest defines model for CreateVaultRequest.
type CreateVaultRequest = externalRef0.CreateVaultRequest

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse = externalRef0.GetUserResponse

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse = externalRef0.HealthCheckResponse

// LoginRequest defines model for LoginRequest.
type LoginRequest = externalRef0.LoginRequest

// LoginResponse defines model for LoginResponse.
type LoginResponse = externalRef0.LoginResponse

// SignupRequest defines model for SignupRequest.
type SignupRequest = externalRef0.SignupRequest

// SignupResponse defines model for SignupResponse.
type SignupResponse = externalRef0.SignupResponse

// UpdateAPIKeyRequest defines model for UpdateAPIKeyRequest.
type UpdateAPIKeyRequest = externalRef0.UpdateAPIKeyRequest

// UpdateVaultRequest defines model for UpdateVaultRequest.
type UpdateVaultRequest = externalRef0.UpdateVaultRequest

// Vault defines model for Vault.
type Vault = externalRef0.Vault

// VaultLite defines model for VaultLite.
type VaultLite = externalRef0.VaultLite

// GetAPIKeysParams defines parameters for GetAPIKeys.
type GetAPIKeysParams struct {
	// PageSize Number of API keys per page (default 20, max 1000)
	PageSize int `form:"pageSize" json:"pageSize"`

	// PageIndex Page index, starting from 1 (default 1)
	PageIndex int `form:"pageIndex" json:"pageIndex"`
}

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	// StartDate Filter logs from this date (ISO 8601 format)
	StartDate *time.Time `form:"startDate,omitempty" json:"startDate,omitempty"`

	// EndDate Filter logs until this date (ISO 8601 format)
	EndDate *time.Time `form:"endDate,omitempty" json:"endDate,omitempty"`

	// VaultUniqueId Filter logs by vault unique ID
	VaultUniqueId *string `form:"vaultUniqueId,omitempty" json:"vaultUniqueId,omitempty"`

	// PageSize Number of logs per page (default 100, max 1000)
	PageSize int `form:"pageSize" json:"pageSize"`

	// PageIndex Page index, starting from 0 (default 0)
	PageIndex int `form:"pageIndex" json:"pageIndex"`
}

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// UpdateAPIKeyJSONRequestBody defines body for UpdateAPIKey for application/json ContentType.
type UpdateAPIKeyJSONRequestBody = UpdateAPIKeyRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// CreateVaultJSONRequestBody defines body for CreateVault for application/json ContentType.
type CreateVaultJSONRequestBody = CreateVaultRequest

// UpdateVaultJSONRequestBody defines body for UpdateVault for application/json ContentType.
type UpdateVaultJSONRequestBody = UpdateVaultRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/api-keys)
	GetAPIKeys(c *fiber.Ctx, params GetAPIKeysParams) error

	// (POST /api/api-keys)
	CreateAPIKey(c *fiber.Ctx) error

	// (DELETE /api/api-keys/{id})
	DeleteAPIKey(c *fiber.Ctx, id int64) error

	// (PATCH /api/api-keys/{id})
	UpdateAPIKey(c *fiber.Ctx, id int64) error

	// (GET /api/audit-logs)
	GetAuditLogs(c *fiber.Ctx, params GetAuditLogsParams) error

	// (POST /api/auth/login)
	Login(c *fiber.Ctx) error

	// (GET /api/auth/logout)
	Logout(c *fiber.Ctx) error

	// (POST /api/auth/signup)
	Signup(c *fiber.Ctx) error

	// (GET /api/health)
	Health(c *fiber.Ctx) error

	// (GET /api/user)
	GetCurrentUser(c *fiber.Ctx) error

	// (GET /api/vaults)
	GetVaults(c *fiber.Ctx) error

	// (POST /api/vaults)
	CreateVault(c *fiber.Ctx) error

	// (DELETE /api/vaults/{uniqueId})
	DeleteVault(c *fiber.Ctx, uniqueId string) error

	// (GET /api/vaults/{uniqueId})
	GetVault(c *fiber.Ctx, uniqueId string) error

	// (PUT /api/vaults/{uniqueId})
	UpdateVault(c *fiber.Ctx, uniqueId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) GetAPIKeys(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAPIKeysParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Required query parameter "pageIndex" -------------

	if paramValue := c.Query("pageIndex"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageIndex is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageIndex", query, &params.PageIndex)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageIndex: %w", err).Error())
	}

	return siw.Handler.GetAPIKeys(c, params)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(c *fiber.Ctx) error {

	return siw.Handler.CreateAPIKey(c)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.DeleteAPIKey(c, id)
}

// UpdateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) UpdateAPIKey(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.UpdateAPIKey(c, id)
}

// GetAuditLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAuditLogs(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditLogsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter startDate: %w", err).Error())
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter endDate: %w", err).Error())
	}

	// ------------- Optional query parameter "vaultUniqueId" -------------

	err = runtime.BindQueryParameter("form", true, false, "vaultUniqueId", query, &params.VaultUniqueId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter vaultUniqueId: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Required query parameter "pageIndex" -------------

	if paramValue := c.Query("pageIndex"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageIndex is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageIndex", query, &params.PageIndex)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageIndex: %w", err).Error())
	}

	return siw.Handler.GetAuditLogs(c, params)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *fiber.Ctx) error {

	return siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *fiber.Ctx) error {

	return siw.Handler.Logout(c)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(c *fiber.Ctx) error {

	return siw.Handler.Signup(c)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *fiber.Ctx) error {

	return siw.Handler.Health(c)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(c *fiber.Ctx) error {

	return siw.Handler.GetCurrentUser(c)
}

// GetVaults operation middleware
func (siw *ServerInterfaceWrapper) GetVaults(c *fiber.Ctx) error {

	return siw.Handler.GetVaults(c)
}

// CreateVault operation middleware
func (siw *ServerInterfaceWrapper) CreateVault(c *fiber.Ctx) error {

	return siw.Handler.CreateVault(c)
}

// DeleteVault operation middleware
func (siw *ServerInterfaceWrapper) DeleteVault(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "uniqueId" -------------
	var uniqueId string

	err = runtime.BindStyledParameterWithOptions("simple", "uniqueId", c.Params("uniqueId"), &uniqueId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter uniqueId: %w", err).Error())
	}

	return siw.Handler.DeleteVault(c, uniqueId)
}

// GetVault operation middleware
func (siw *ServerInterfaceWrapper) GetVault(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "uniqueId" -------------
	var uniqueId string

	err = runtime.BindStyledParameterWithOptions("simple", "uniqueId", c.Params("uniqueId"), &uniqueId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter uniqueId: %w", err).Error())
	}

	return siw.Handler.GetVault(c, uniqueId)
}

// UpdateVault operation middleware
func (siw *ServerInterfaceWrapper) UpdateVault(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "uniqueId" -------------
	var uniqueId string

	err = runtime.BindStyledParameterWithOptions("simple", "uniqueId", c.Params("uniqueId"), &uniqueId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter uniqueId: %w", err).Error())
	}

	return siw.Handler.UpdateVault(c, uniqueId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/api-keys", wrapper.GetAPIKeys)

	router.Post(options.BaseURL+"/api/api-keys", wrapper.CreateAPIKey)

	router.Delete(options.BaseURL+"/api/api-keys/:id", wrapper.DeleteAPIKey)

	router.Patch(options.BaseURL+"/api/api-keys/:id", wrapper.UpdateAPIKey)

	router.Get(options.BaseURL+"/api/audit-logs", wrapper.GetAuditLogs)

	router.Post(options.BaseURL+"/api/auth/login", wrapper.Login)

	router.Get(options.BaseURL+"/api/auth/logout", wrapper.Logout)

	router.Post(options.BaseURL+"/api/auth/signup", wrapper.Signup)

	router.Get(options.BaseURL+"/api/health", wrapper.Health)

	router.Get(options.BaseURL+"/api/user", wrapper.GetCurrentUser)

	router.Get(options.BaseURL+"/api/vaults", wrapper.GetVaults)

	router.Post(options.BaseURL+"/api/vaults", wrapper.CreateVault)

	router.Delete(options.BaseURL+"/api/vaults/:uniqueId", wrapper.DeleteVault)

	router.Get(options.BaseURL+"/api/vaults/:uniqueId", wrapper.GetVault)

	router.Put(options.BaseURL+"/api/vaults/:uniqueId", wrapper.UpdateVault)

}

type GetAPIKeysRequestObject struct {
	Params GetAPIKeysParams
}

type GetAPIKeysResponseObject interface {
	VisitGetAPIKeysResponse(ctx *fiber.Ctx) error
}

type GetAPIKeys200JSONResponse APIKeysResponse

func (response GetAPIKeys200JSONResponse) VisitGetAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateAPIKeyRequestObject struct {
	Body *CreateAPIKeyJSONRequestBody
}

type CreateAPIKeyResponseObject interface {
	VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error
}

type CreateAPIKey201JSONResponse CreateAPIKeyResponse

func (response CreateAPIKey201JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type DeleteAPIKeyRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteAPIKeyResponseObject interface {
	VisitDeleteAPIKeyResponse(ctx *fiber.Ctx) error
}

type DeleteAPIKey204Response struct {
}

func (response DeleteAPIKey204Response) VisitDeleteAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type UpdateAPIKeyRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateAPIKeyJSONRequestBody
}

type UpdateAPIKeyResponseObject interface {
	VisitUpdateAPIKeyResponse(ctx *fiber.Ctx) error
}

type UpdateAPIKey200JSONResponse APIKey

func (response UpdateAPIKey200JSONResponse) VisitUpdateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetAuditLogsRequestObject struct {
	Params GetAuditLogsParams
}

type GetAuditLogsResponseObject interface {
	VisitGetAuditLogsResponse(ctx *fiber.Ctx) error
}

type GetAuditLogs200JSONResponse AuditLogsResponse

func (response GetAuditLogs200JSONResponse) VisitGetAuditLogsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(ctx *fiber.Ctx) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(ctx *fiber.Ctx) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(ctx *fiber.Ctx) error
}

type Signup200JSONResponse SignupResponse

func (response Signup200JSONResponse) VisitSignupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(ctx *fiber.Ctx) error
}

type Health200JSONResponse HealthCheckResponse

func (response Health200JSONResponse) VisitHealthResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(ctx *fiber.Ctx) error
}

type GetCurrentUser200JSONResponse GetUserResponse

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetVaultsRequestObject struct {
}

type GetVaultsResponseObject interface {
	VisitGetVaultsResponse(ctx *fiber.Ctx) error
}

type GetVaults200JSONResponse []VaultLite

func (response GetVaults200JSONResponse) VisitGetVaultsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateVaultRequestObject struct {
	Body *CreateVaultJSONRequestBody
}

type CreateVaultResponseObject interface {
	VisitCreateVaultResponse(ctx *fiber.Ctx) error
}

type CreateVault201JSONResponse Vault

func (response CreateVault201JSONResponse) VisitCreateVaultResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type DeleteVaultRequestObject struct {
	UniqueId string `json:"uniqueId"`
}

type DeleteVaultResponseObject interface {
	VisitDeleteVaultResponse(ctx *fiber.Ctx) error
}

type DeleteVault204Response struct {
}

func (response DeleteVault204Response) VisitDeleteVaultResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type GetVaultRequestObject struct {
	UniqueId string `json:"uniqueId"`
}

type GetVaultResponseObject interface {
	VisitGetVaultResponse(ctx *fiber.Ctx) error
}

type GetVault200JSONResponse Vault

func (response GetVault200JSONResponse) VisitGetVaultResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateVaultRequestObject struct {
	UniqueId string `json:"uniqueId"`
	Body     *UpdateVaultJSONRequestBody
}

type UpdateVaultResponseObject interface {
	VisitUpdateVaultResponse(ctx *fiber.Ctx) error
}

type UpdateVault200JSONResponse Vault

func (response UpdateVault200JSONResponse) VisitUpdateVaultResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/api-keys)
	GetAPIKeys(ctx context.Context, request GetAPIKeysRequestObject) (GetAPIKeysResponseObject, error)

	// (POST /api/api-keys)
	CreateAPIKey(ctx context.Context, request CreateAPIKeyRequestObject) (CreateAPIKeyResponseObject, error)

	// (DELETE /api/api-keys/{id})
	DeleteAPIKey(ctx context.Context, request DeleteAPIKeyRequestObject) (DeleteAPIKeyResponseObject, error)

	// (PATCH /api/api-keys/{id})
	UpdateAPIKey(ctx context.Context, request UpdateAPIKeyRequestObject) (UpdateAPIKeyResponseObject, error)

	// (GET /api/audit-logs)
	GetAuditLogs(ctx context.Context, request GetAuditLogsRequestObject) (GetAuditLogsResponseObject, error)

	// (POST /api/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (GET /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)

	// (POST /api/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)

	// (GET /api/health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (GET /api/user)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)

	// (GET /api/vaults)
	GetVaults(ctx context.Context, request GetVaultsRequestObject) (GetVaultsResponseObject, error)

	// (POST /api/vaults)
	CreateVault(ctx context.Context, request CreateVaultRequestObject) (CreateVaultResponseObject, error)

	// (DELETE /api/vaults/{uniqueId})
	DeleteVault(ctx context.Context, request DeleteVaultRequestObject) (DeleteVaultResponseObject, error)

	// (GET /api/vaults/{uniqueId})
	GetVault(ctx context.Context, request GetVaultRequestObject) (GetVaultResponseObject, error)

	// (PUT /api/vaults/{uniqueId})
	UpdateVault(ctx context.Context, request UpdateVaultRequestObject) (UpdateVaultResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAPIKeys operation middleware
func (sh *strictHandler) GetAPIKeys(ctx *fiber.Ctx, params GetAPIKeysParams) error {
	var request GetAPIKeysRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIKeys(ctx.UserContext(), request.(GetAPIKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIKeys")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetAPIKeysResponseObject); ok {
		if err := validResponse.VisitGetAPIKeysResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateAPIKey operation middleware
func (sh *strictHandler) CreateAPIKey(ctx *fiber.Ctx) error {
	var request CreateAPIKeyRequestObject

	var body CreateAPIKeyJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIKey(ctx.UserContext(), request.(CreateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateAPIKeyResponseObject); ok {
		if err := validResponse.VisitCreateAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteAPIKey operation middleware
func (sh *strictHandler) DeleteAPIKey(ctx *fiber.Ctx, id int64) error {
	var request DeleteAPIKeyRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAPIKey(ctx.UserContext(), request.(DeleteAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeleteAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateAPIKey operation middleware
func (sh *strictHandler) UpdateAPIKey(ctx *fiber.Ctx, id int64) error {
	var request UpdateAPIKeyRequestObject

	request.Id = id

	var body UpdateAPIKeyJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAPIKey(ctx.UserContext(), request.(UpdateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateAPIKeyResponseObject); ok {
		if err := validResponse.VisitUpdateAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuditLogs operation middleware
func (sh *strictHandler) GetAuditLogs(ctx *fiber.Ctx, params GetAuditLogsParams) error {
	var request GetAuditLogsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuditLogs(ctx.UserContext(), request.(GetAuditLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuditLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetAuditLogsResponseObject); ok {
		if err := validResponse.VisitGetAuditLogsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *fiber.Ctx) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.UserContext(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *fiber.Ctx) error {
	var request LogoutRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.UserContext(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Signup operation middleware
func (sh *strictHandler) Signup(ctx *fiber.Ctx) error {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx.UserContext(), request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *fiber.Ctx) error {
	var request HealthRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx.UserContext(), request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx *fiber.Ctx) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.UserContext(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetVaults operation middleware
func (sh *strictHandler) GetVaults(ctx *fiber.Ctx) error {
	var request GetVaultsRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetVaults(ctx.UserContext(), request.(GetVaultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVaults")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetVaultsResponseObject); ok {
		if err := validResponse.VisitGetVaultsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateVault operation middleware
func (sh *strictHandler) CreateVault(ctx *fiber.Ctx) error {
	var request CreateVaultRequestObject

	var body CreateVaultJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVault(ctx.UserContext(), request.(CreateVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateVaultResponseObject); ok {
		if err := validResponse.VisitCreateVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteVault operation middleware
func (sh *strictHandler) DeleteVault(ctx *fiber.Ctx, uniqueId string) error {
	var request DeleteVaultRequestObject

	request.UniqueId = uniqueId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVault(ctx.UserContext(), request.(DeleteVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteVaultResponseObject); ok {
		if err := validResponse.VisitDeleteVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetVault operation middleware
func (sh *strictHandler) GetVault(ctx *fiber.Ctx, uniqueId string) error {
	var request GetVaultRequestObject

	request.UniqueId = uniqueId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetVault(ctx.UserContext(), request.(GetVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetVaultResponseObject); ok {
		if err := validResponse.VisitGetVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateVault operation middleware
func (sh *strictHandler) UpdateVault(ctx *fiber.Ctx, uniqueId string) error {
	var request UpdateVaultRequestObject

	request.UniqueId = uniqueId

	var body UpdateVaultJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateVault(ctx.UserContext(), request.(UpdateVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateVaultResponseObject); ok {
		if err := validResponse.VisitUpdateVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
