// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditLogAction.
const (
	CreateApiKey AuditLogAction = "create_api_key"
	CreateVault  AuditLogAction = "create_vault"
	DeleteApiKey AuditLogAction = "delete_api_key"
	DeleteVault  AuditLogAction = "delete_vault"
	LoginUser    AuditLogAction = "login_user"
	LogoutUser   AuditLogAction = "logout_user"
	ReadVault    AuditLogAction = "read_vault"
	RegisterUser AuditLogAction = "register_user"
	UpdateApiKey AuditLogAction = "update_api_key"
	UpdateVault  AuditLogAction = "update_vault"
)

// APIKey defines model for APIKey.
type APIKey struct {
	// CreatedAt When the key was created
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Optional expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Id Unique API key ID
	Id int64 `json:"id"`

	// IsActive Whether the key is currently active
	IsActive bool `json:"is_active"`

	// LastUsedAt When the key was last used
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// Name Human-readable name for the API key
	Name string `json:"name"`

	// UpdatedAt When the key was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Vaults Array of vaults this key can access (null/empty = all user's vaults)
	Vaults *[]VaultLite `json:"vaults,omitempty"`
}

// AuditLog defines model for AuditLog.
type AuditLog struct {
	// Action Type of action performed
	Action AuditLogAction `json:"action"`
	ApiKey *APIKey        `json:"api_key,omitempty"`

	// CreatedAt When the action occurred
	CreatedAt time.Time `json:"created_at"`

	// IpAddress IP address from which the action was performed
	IpAddress *string `json:"ip_address,omitempty"`

	// UserAgent User agent string from the client
	UserAgent *string    `json:"user_agent,omitempty"`
	Vault     *VaultLite `json:"vault,omitempty"`
}

// AuditLogAction Type of action performed
type AuditLogAction string

// AuditLogsResponse defines model for AuditLogsResponse.
type AuditLogsResponse struct {
	AuditLogs []AuditLog `json:"audit_logs"`

	// PageIndex Current page index (starting from 0)
	PageIndex int `json:"pageIndex"`

	// PageSize Number of logs per page
	PageSize int `json:"pageSize"`

	// TotalCount Total number of logs matching the filter criteria
	TotalCount int `json:"total_count"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// ExpiresAt Optional expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Name Human-readable name for the API key
	Name string `json:"name"`

	// VaultUniqueIds Array of vault unique IDs this key can access (empty = all user's vaults)
	VaultUniqueIds *[]string `json:"vault_unique_ids,omitempty"`
}

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	ApiKey APIKey `json:"api_key"`

	// Key The generated API key (only shown once)
	Key string `json:"key"`
}

// CreateVaultRequest defines model for CreateVaultRequest.
type CreateVaultRequest struct {
	// Category Category/type of vault
	Category *string `json:"category,omitempty"`

	// Description Human-readable description
	Description *string `json:"description,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`

	// Value Value to be encrypted and stored
	Value string `json:"value"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	Avatar *string             `json:"avatar,omitempty"`
	Email  openapi_types.Email `json:"email"`
	Name   *string             `json:"name,omitempty"`
}

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	Status    *string    `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// SignupResponse defines model for SignupResponse.
type SignupResponse struct {
	Token string `json:"token"`
}

// UpdateAPIKeyRequest defines model for UpdateAPIKeyRequest.
type UpdateAPIKeyRequest struct {
	// ExpiresAt Optional expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// IsActive Enable or disable the API key
	IsActive *bool `json:"is_active,omitempty"`

	// Name Human-readable name for the API key
	Name *string `json:"name,omitempty"`

	// VaultUniqueIds Array of vault unique IDs this key can access (empty = all user's vaults)
	VaultUniqueIds *[]string `json:"vault_unique_ids,omitempty"`
}

// UpdateVaultRequest defines model for UpdateVaultRequest.
type UpdateVaultRequest struct {
	// Category Category/type of vault
	Category *string `json:"category,omitempty"`

	// Description Human-readable description
	Description *string `json:"description,omitempty"`

	// Name Human-readable name
	Name *string `json:"name,omitempty"`

	// Value Value to be encrypted and stored
	Value *string `json:"value,omitempty"`
}

// Vault defines model for Vault.
type Vault struct {
	// Category Category/type of vault
	Category  *string    `json:"category,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Human-readable description
	Description *string `json:"description,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`

	// UniqueId Unique identifier for the vault
	UniqueId  string     `json:"unique_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// UserId ID of the user who owns this vault
	UserId *int64 `json:"user_id,omitempty"`

	// Value Encrypted value
	Value string `json:"value"`
}

// VaultLite defines model for VaultLite.
type VaultLite struct {
	// Category Category/type of vault
	Category *string `json:"category,omitempty"`

	// Description Human-readable description
	Description *string `json:"description,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`

	// UniqueId Unique identifier for the vault
	UniqueId  string     `json:"unique_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	// StartDate Filter logs from this date (ISO 8601 format)
	StartDate *time.Time `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Filter logs until this date (ISO 8601 format)
	EndDate *time.Time `form:"end_date,omitempty" json:"end_date,omitempty"`

	// VaultUniqueId Filter logs by vault unique ID
	VaultUniqueId *string `form:"vault_unique_id,omitempty" json:"vault_unique_id,omitempty"`

	// PageSize Number of logs per page (default 100, max 1000)
	PageSize int `form:"pageSize" json:"pageSize"`

	// PageIndex Page index, starting from 0 (default 0)
	PageIndex int `form:"pageIndex" json:"pageIndex"`
}

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// UpdateAPIKeyJSONRequestBody defines body for UpdateAPIKey for application/json ContentType.
type UpdateAPIKeyJSONRequestBody = UpdateAPIKeyRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// CreateVaultJSONRequestBody defines body for CreateVault for application/json ContentType.
type CreateVaultJSONRequestBody = CreateVaultRequest

// UpdateVaultJSONRequestBody defines body for UpdateVault for application/json ContentType.
type UpdateVaultJSONRequestBody = UpdateVaultRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/api-keys)
	GetAPIKeys(c *fiber.Ctx) error

	// (POST /api/api-keys)
	CreateAPIKey(c *fiber.Ctx) error

	// (DELETE /api/api-keys/{id})
	DeleteAPIKey(c *fiber.Ctx, id int64) error

	// (PATCH /api/api-keys/{id})
	UpdateAPIKey(c *fiber.Ctx, id int64) error

	// (GET /api/audit-logs)
	GetAuditLogs(c *fiber.Ctx, params GetAuditLogsParams) error

	// (POST /api/auth/login)
	Login(c *fiber.Ctx) error

	// (GET /api/auth/logout)
	Logout(c *fiber.Ctx) error

	// (POST /api/auth/signup)
	Signup(c *fiber.Ctx) error

	// (GET /api/health)
	Health(c *fiber.Ctx) error

	// (GET /api/user)
	GetCurrentUser(c *fiber.Ctx) error

	// (GET /api/vaults)
	GetVaults(c *fiber.Ctx) error

	// (POST /api/vaults)
	CreateVault(c *fiber.Ctx) error

	// (DELETE /api/vaults/{unique_id})
	DeleteVault(c *fiber.Ctx, uniqueId string) error

	// (GET /api/vaults/{unique_id})
	GetVault(c *fiber.Ctx, uniqueId string) error

	// (PUT /api/vaults/{unique_id})
	UpdateVault(c *fiber.Ctx, uniqueId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) GetAPIKeys(c *fiber.Ctx) error {

	return siw.Handler.GetAPIKeys(c)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(c *fiber.Ctx) error {

	return siw.Handler.CreateAPIKey(c)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.DeleteAPIKey(c, id)
}

// UpdateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) UpdateAPIKey(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.UpdateAPIKey(c, id)
}

// GetAuditLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAuditLogs(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditLogsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter start_date: %w", err).Error())
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter end_date: %w", err).Error())
	}

	// ------------- Optional query parameter "vault_unique_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "vault_unique_id", query, &params.VaultUniqueId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter vault_unique_id: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Required query parameter "pageIndex" -------------

	if paramValue := c.Query("pageIndex"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageIndex is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageIndex", query, &params.PageIndex)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageIndex: %w", err).Error())
	}

	return siw.Handler.GetAuditLogs(c, params)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *fiber.Ctx) error {

	return siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *fiber.Ctx) error {

	return siw.Handler.Logout(c)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(c *fiber.Ctx) error {

	return siw.Handler.Signup(c)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *fiber.Ctx) error {

	return siw.Handler.Health(c)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(c *fiber.Ctx) error {

	return siw.Handler.GetCurrentUser(c)
}

// GetVaults operation middleware
func (siw *ServerInterfaceWrapper) GetVaults(c *fiber.Ctx) error {

	return siw.Handler.GetVaults(c)
}

// CreateVault operation middleware
func (siw *ServerInterfaceWrapper) CreateVault(c *fiber.Ctx) error {

	return siw.Handler.CreateVault(c)
}

// DeleteVault operation middleware
func (siw *ServerInterfaceWrapper) DeleteVault(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "unique_id" -------------
	var uniqueId string

	err = runtime.BindStyledParameterWithOptions("simple", "unique_id", c.Params("unique_id"), &uniqueId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter unique_id: %w", err).Error())
	}

	return siw.Handler.DeleteVault(c, uniqueId)
}

// GetVault operation middleware
func (siw *ServerInterfaceWrapper) GetVault(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "unique_id" -------------
	var uniqueId string

	err = runtime.BindStyledParameterWithOptions("simple", "unique_id", c.Params("unique_id"), &uniqueId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter unique_id: %w", err).Error())
	}

	return siw.Handler.GetVault(c, uniqueId)
}

// UpdateVault operation middleware
func (siw *ServerInterfaceWrapper) UpdateVault(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "unique_id" -------------
	var uniqueId string

	err = runtime.BindStyledParameterWithOptions("simple", "unique_id", c.Params("unique_id"), &uniqueId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter unique_id: %w", err).Error())
	}

	return siw.Handler.UpdateVault(c, uniqueId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/api-keys", wrapper.GetAPIKeys)

	router.Post(options.BaseURL+"/api/api-keys", wrapper.CreateAPIKey)

	router.Delete(options.BaseURL+"/api/api-keys/:id", wrapper.DeleteAPIKey)

	router.Patch(options.BaseURL+"/api/api-keys/:id", wrapper.UpdateAPIKey)

	router.Get(options.BaseURL+"/api/audit-logs", wrapper.GetAuditLogs)

	router.Post(options.BaseURL+"/api/auth/login", wrapper.Login)

	router.Get(options.BaseURL+"/api/auth/logout", wrapper.Logout)

	router.Post(options.BaseURL+"/api/auth/signup", wrapper.Signup)

	router.Get(options.BaseURL+"/api/health", wrapper.Health)

	router.Get(options.BaseURL+"/api/user", wrapper.GetCurrentUser)

	router.Get(options.BaseURL+"/api/vaults", wrapper.GetVaults)

	router.Post(options.BaseURL+"/api/vaults", wrapper.CreateVault)

	router.Delete(options.BaseURL+"/api/vaults/:unique_id", wrapper.DeleteVault)

	router.Get(options.BaseURL+"/api/vaults/:unique_id", wrapper.GetVault)

	router.Put(options.BaseURL+"/api/vaults/:unique_id", wrapper.UpdateVault)

}

type GetAPIKeysRequestObject struct {
}

type GetAPIKeysResponseObject interface {
	VisitGetAPIKeysResponse(ctx *fiber.Ctx) error
}

type GetAPIKeys200JSONResponse []APIKey

func (response GetAPIKeys200JSONResponse) VisitGetAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateAPIKeyRequestObject struct {
	Body *CreateAPIKeyJSONRequestBody
}

type CreateAPIKeyResponseObject interface {
	VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error
}

type CreateAPIKey201JSONResponse CreateAPIKeyResponse

func (response CreateAPIKey201JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type DeleteAPIKeyRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteAPIKeyResponseObject interface {
	VisitDeleteAPIKeyResponse(ctx *fiber.Ctx) error
}

type DeleteAPIKey204Response struct {
}

func (response DeleteAPIKey204Response) VisitDeleteAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type UpdateAPIKeyRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateAPIKeyJSONRequestBody
}

type UpdateAPIKeyResponseObject interface {
	VisitUpdateAPIKeyResponse(ctx *fiber.Ctx) error
}

type UpdateAPIKey200JSONResponse APIKey

func (response UpdateAPIKey200JSONResponse) VisitUpdateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetAuditLogsRequestObject struct {
	Params GetAuditLogsParams
}

type GetAuditLogsResponseObject interface {
	VisitGetAuditLogsResponse(ctx *fiber.Ctx) error
}

type GetAuditLogs200JSONResponse AuditLogsResponse

func (response GetAuditLogs200JSONResponse) VisitGetAuditLogsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(ctx *fiber.Ctx) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(ctx *fiber.Ctx) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(ctx *fiber.Ctx) error
}

type Signup200JSONResponse SignupResponse

func (response Signup200JSONResponse) VisitSignupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(ctx *fiber.Ctx) error
}

type Health200JSONResponse HealthCheckResponse

func (response Health200JSONResponse) VisitHealthResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(ctx *fiber.Ctx) error
}

type GetCurrentUser200JSONResponse GetUserResponse

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetVaultsRequestObject struct {
}

type GetVaultsResponseObject interface {
	VisitGetVaultsResponse(ctx *fiber.Ctx) error
}

type GetVaults200JSONResponse []VaultLite

func (response GetVaults200JSONResponse) VisitGetVaultsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateVaultRequestObject struct {
	Body *CreateVaultJSONRequestBody
}

type CreateVaultResponseObject interface {
	VisitCreateVaultResponse(ctx *fiber.Ctx) error
}

type CreateVault201JSONResponse Vault

func (response CreateVault201JSONResponse) VisitCreateVaultResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type DeleteVaultRequestObject struct {
	UniqueId string `json:"unique_id"`
}

type DeleteVaultResponseObject interface {
	VisitDeleteVaultResponse(ctx *fiber.Ctx) error
}

type DeleteVault204Response struct {
}

func (response DeleteVault204Response) VisitDeleteVaultResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type GetVaultRequestObject struct {
	UniqueId string `json:"unique_id"`
}

type GetVaultResponseObject interface {
	VisitGetVaultResponse(ctx *fiber.Ctx) error
}

type GetVault200JSONResponse Vault

func (response GetVault200JSONResponse) VisitGetVaultResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateVaultRequestObject struct {
	UniqueId string `json:"unique_id"`
	Body     *UpdateVaultJSONRequestBody
}

type UpdateVaultResponseObject interface {
	VisitUpdateVaultResponse(ctx *fiber.Ctx) error
}

type UpdateVault200JSONResponse Vault

func (response UpdateVault200JSONResponse) VisitUpdateVaultResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/api-keys)
	GetAPIKeys(ctx context.Context, request GetAPIKeysRequestObject) (GetAPIKeysResponseObject, error)

	// (POST /api/api-keys)
	CreateAPIKey(ctx context.Context, request CreateAPIKeyRequestObject) (CreateAPIKeyResponseObject, error)

	// (DELETE /api/api-keys/{id})
	DeleteAPIKey(ctx context.Context, request DeleteAPIKeyRequestObject) (DeleteAPIKeyResponseObject, error)

	// (PATCH /api/api-keys/{id})
	UpdateAPIKey(ctx context.Context, request UpdateAPIKeyRequestObject) (UpdateAPIKeyResponseObject, error)

	// (GET /api/audit-logs)
	GetAuditLogs(ctx context.Context, request GetAuditLogsRequestObject) (GetAuditLogsResponseObject, error)

	// (POST /api/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (GET /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)

	// (POST /api/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)

	// (GET /api/health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (GET /api/user)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)

	// (GET /api/vaults)
	GetVaults(ctx context.Context, request GetVaultsRequestObject) (GetVaultsResponseObject, error)

	// (POST /api/vaults)
	CreateVault(ctx context.Context, request CreateVaultRequestObject) (CreateVaultResponseObject, error)

	// (DELETE /api/vaults/{unique_id})
	DeleteVault(ctx context.Context, request DeleteVaultRequestObject) (DeleteVaultResponseObject, error)

	// (GET /api/vaults/{unique_id})
	GetVault(ctx context.Context, request GetVaultRequestObject) (GetVaultResponseObject, error)

	// (PUT /api/vaults/{unique_id})
	UpdateVault(ctx context.Context, request UpdateVaultRequestObject) (UpdateVaultResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAPIKeys operation middleware
func (sh *strictHandler) GetAPIKeys(ctx *fiber.Ctx) error {
	var request GetAPIKeysRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIKeys(ctx.UserContext(), request.(GetAPIKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIKeys")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetAPIKeysResponseObject); ok {
		if err := validResponse.VisitGetAPIKeysResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateAPIKey operation middleware
func (sh *strictHandler) CreateAPIKey(ctx *fiber.Ctx) error {
	var request CreateAPIKeyRequestObject

	var body CreateAPIKeyJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIKey(ctx.UserContext(), request.(CreateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateAPIKeyResponseObject); ok {
		if err := validResponse.VisitCreateAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteAPIKey operation middleware
func (sh *strictHandler) DeleteAPIKey(ctx *fiber.Ctx, id int64) error {
	var request DeleteAPIKeyRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAPIKey(ctx.UserContext(), request.(DeleteAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeleteAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateAPIKey operation middleware
func (sh *strictHandler) UpdateAPIKey(ctx *fiber.Ctx, id int64) error {
	var request UpdateAPIKeyRequestObject

	request.Id = id

	var body UpdateAPIKeyJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAPIKey(ctx.UserContext(), request.(UpdateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateAPIKeyResponseObject); ok {
		if err := validResponse.VisitUpdateAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuditLogs operation middleware
func (sh *strictHandler) GetAuditLogs(ctx *fiber.Ctx, params GetAuditLogsParams) error {
	var request GetAuditLogsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuditLogs(ctx.UserContext(), request.(GetAuditLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuditLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetAuditLogsResponseObject); ok {
		if err := validResponse.VisitGetAuditLogsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *fiber.Ctx) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.UserContext(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *fiber.Ctx) error {
	var request LogoutRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.UserContext(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Signup operation middleware
func (sh *strictHandler) Signup(ctx *fiber.Ctx) error {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx.UserContext(), request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *fiber.Ctx) error {
	var request HealthRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx.UserContext(), request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx *fiber.Ctx) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.UserContext(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetVaults operation middleware
func (sh *strictHandler) GetVaults(ctx *fiber.Ctx) error {
	var request GetVaultsRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetVaults(ctx.UserContext(), request.(GetVaultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVaults")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetVaultsResponseObject); ok {
		if err := validResponse.VisitGetVaultsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateVault operation middleware
func (sh *strictHandler) CreateVault(ctx *fiber.Ctx) error {
	var request CreateVaultRequestObject

	var body CreateVaultJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVault(ctx.UserContext(), request.(CreateVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateVaultResponseObject); ok {
		if err := validResponse.VisitCreateVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteVault operation middleware
func (sh *strictHandler) DeleteVault(ctx *fiber.Ctx, uniqueId string) error {
	var request DeleteVaultRequestObject

	request.UniqueId = uniqueId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVault(ctx.UserContext(), request.(DeleteVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteVaultResponseObject); ok {
		if err := validResponse.VisitDeleteVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetVault operation middleware
func (sh *strictHandler) GetVault(ctx *fiber.Ctx, uniqueId string) error {
	var request GetVaultRequestObject

	request.UniqueId = uniqueId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetVault(ctx.UserContext(), request.(GetVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetVaultResponseObject); ok {
		if err := validResponse.VisitGetVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateVault operation middleware
func (sh *strictHandler) UpdateVault(ctx *fiber.Ctx, uniqueId string) error {
	var request UpdateVaultRequestObject

	request.UniqueId = uniqueId

	var body UpdateVaultJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateVault(ctx.UserContext(), request.(UpdateVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateVault")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateVaultResponseObject); ok {
		if err := validResponse.VisitUpdateVaultResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
