name: Build with Embedded Web Assets

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10.15.1
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: 'apps/web/pnpm-lock.yaml'
    
    - name: Install web dependencies
      run: |
        cd apps/web
        pnpm install --frozen-lockfile
    
    - name: Build web application
      run: |
        cd apps/web
        pnpm build
    
    - name: Copy dist to embed directory
      run: |
        mkdir -p internal/embed
        cp -r apps/web/dist internal/embed/
    
    - name: Build Go binaries
      run: |
        go build -o vault-hub-server ./apps/server
        go build -o vault-hub-cli ./apps/cli
        go build -o vault-hub-cron ./apps/cron
    
    - name: Test binaries
      run: |
        ./vault-hub-cli version || echo "CLI version check"
        ls -lh vault-hub-*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          vault-hub-server
          vault-hub-cli
          vault-hub-cron
        retention-days: 7