name: Database Connection Tests

env:
  GO_VERSION: "1.24"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test SQLite Connection
        run: |
          export JWT_SECRET=secret
          export DATABASE_TYPE=sqlite
          export DATABASE_URL=file::memory:?cache=shared
          go test -v ./model -run TestDatabaseConnection

  test-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test MySQL Connection
        run: |
          export JWT_SECRET=secret
          export DATABASE_TYPE=mysql
          export DATABASE_URL="root:root@tcp(localhost:3306)/testdb?charset=utf8mb4&parseTime=True&loc=Local"
          go test -v ./model -run TestDatabaseConnection

  test-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test PostgreSQL Connection
        run: |
          export JWT_SECRET=secret
          export DATABASE_TYPE=postgres
          export DATABASE_URL="postgres://postgres:postgres@localhost/testdb"
          go test -v ./model -run TestDatabaseConnection
