name: Build and Publish Client
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://npm.pkg.github.com
          scope: '@lwshen'
      - name: Set env
        run: echo "TAG=0.$(date +'%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"
      - name: Generate Typescript Fetch Client Library
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          openapi-file: packages/api/openapi/api.yaml
          generator-tag: v7.13.0
          command-args: --additional-properties=npmName=@lwshen/vault-hub-ts-fetch-client --additional-properties=npmVersion=${{ env.TAG }} --additional-properties=useSingleRequestParameter=false --git-user-id lwshen --git-repo-id vault-hub
      - name: Publish to GitHub Packages
        run: |
          # Push to separate repository only outside of pull_request events
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            cd typescript-fetch-client
            echo ${{ env.TAG }}
            cat package.json
            npm install
            npm run build
            npm publish
          else
            echo "Skipping push during pull_request event"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node for npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
      - name: Set env
        run: echo "TAG=0.$(date +'%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"
      - name: Generate Typescript Fetch Client Library
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          openapi-file: packages/api/openapi/api.yaml
          generator-tag: v7.13.0
          command-args: --additional-properties=npmName=@lwshen/vault-hub-ts-fetch-client --additional-properties=useSingleRequestParameter=false --additional-properties=npmVersion=${{ env.TAG }} --git-user-id lwshen --git-repo-id vault-hub
      - name: Build package
        run: |
          pwd
          ls -al
          cd typescript-fetch-client
          npm install
          npm run build
      - name: Publish to npm registry
        run: |
          pwd
          ls -al
          # Push to separate repository only outside of pull_request events
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            cd typescript-fetch-client
            npm publish --access public
          else
            echo "Skipping push during pull_request event"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload OpenAPI client artifact
        uses: actions/upload-artifact@v4
        with:
          name: typescript-axios-client
          path: typescript-axios-client
          if-no-files-found: error
