name: Release
on:
  release:
    types:
      - created
permissions:
  contents: write
  pull-requests: read
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/changelog_configuration.json
          outputFile: CHANGELOG.md
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update CHANGELOG.md for ${{ github.event.release.tag_name }}'
          file_pattern: CHANGELOG.md
